return {
	PlaceObj('ModItemCharacterEffectCompositeDef', {
		'Id', "cancel_shot_flashbang",
		'SortKey', 2,
		'object_class', "CharacterEffect",
		'msg_reactions', {
			PlaceObj('MsgReaction', {
				Event = "StatusEffectAdded",
				Handler = function (self, obj, id, stacks)
					local reaction_idx = table.find(self.msg_reactions or empty_table, "Event", "StatusEffectAdded")
					if not reaction_idx then return end
					
					local function exec(self, obj, id, stacks)
					if IsKindOf(obj, "Unit") then
						obj:InterruptPreparedAttack()
						obj:ActivatePerk("MeleeTraining")
						obj:RemoveStatusEffect("BandageInCombat")
						obj:RemoveStatusEffect("CancelShot")
						obj:UpdateMeleeTrainingVisual()
					end
					end
					local _id = GetCharacterEffectId(self)
					if _id == id then exec(self, obj, id, stacks) end
					
				end,
				HandlerCode = function (self, obj, id, stacks)
					if IsKindOf(obj, "Unit") then
						obj:InterruptPreparedAttack()
						obj:ActivatePerk("MeleeTraining")
						obj:RemoveStatusEffect("BandageInCombat")
						obj:RemoveStatusEffect("CancelShot")
						obj:UpdateMeleeTrainingVisual()
					end
				end,
				param_bindings = false,
			}),
		},
		'DisplayName', T(192684063690, --[[ModItemCharacterEffectCompositeDef cancel_shot_flashbang DisplayName]] "Cancel readied attack"),
		'Description', T(335808529700, --[[ModItemCharacterEffectCompositeDef cancel_shot_flashbang Description]] "Removes <color EmStyle>Overwatch</color> and <color EmStyle>Pin Down</color>."),
		'Icon', "UI/Icons/Perks/CancelShotPerk",
	}),
	PlaceObj('ModItemCharacterEffectCompositeDef', {
		'Id', "dazed_flashbang",
		'Parameters', {
			PlaceObj('PresetParamPercent', {
				'Name', "cth_effect",
				'Value', -40,
				'Tag', "<cth_effect>%",
			}),
		},
		'object_class', "CharacterEffect",
		'msg_reactions', {
			PlaceObj('MsgReaction', {
				Event = "StatusEffectAdded",
				Handler = function (self, obj, id, stacks)
					local reaction_idx = table.find(self.msg_reactions or empty_table, "Event", "StatusEffectAdded")
					if not reaction_idx then return end
					
					local function exec(self, obj, id, stacks)
					if IsKindOf(obj, "Unit") then
						obj:SetEffectValue("blinded_start_time", GameTime())
					
					end
					end
					local _id = GetCharacterEffectId(self)
					if _id == id then exec(self, obj, id, stacks) end
					
				end,
				HandlerCode = function (self, obj, id, stacks)
					if IsKindOf(obj, "Unit") then
						obj:SetEffectValue("blinded_start_time", GameTime())
					
					end
				end,
				param_bindings = false,
			}),
			PlaceObj('MsgReaction', {
				Event = "StatusEffectRemoved",
				Handler = function (self, obj, id, stacks, reason)
					local reaction_idx = table.find(self.msg_reactions or empty_table, "Event", "StatusEffectRemoved")
					if not reaction_idx then return end
					
					local function exec(self, obj, id, stacks, reason)
					if IsKindOf(obj, "Unit") then
						obj:SetEffectValue("blinded_start_time")
						ObjModified(obj)
					end
					end
					local _id = GetCharacterEffectId(self)
					if _id == id then exec(self, obj, id, stacks, reason) end
					
				end,
				HandlerCode = function (self, obj, id, stacks, reason)
					if IsKindOf(obj, "Unit") then
						obj:SetEffectValue("blinded_start_time")
						ObjModified(obj)
					end
				end,
				param_bindings = false,
			}),
			PlaceObj('MsgReaction', {
				Event = "UnitBeginTurn",
				Handler = function (self, unit)
					local reaction_idx = table.find(self.msg_reactions or empty_table, "Event", "UnitBeginTurn")
					if not reaction_idx then return end
					
					local function exec(self, unit)
					if not unit:IsDead() then
						EnvEffectTearGasTick(unit, nil, "start turn")
					end
					end
					local id = GetCharacterEffectId(self)
					
					if id then
						if IsKindOf(unit, "StatusEffectObject") and unit:HasStatusEffect(id) then
							exec(self, unit)
						end
					else
						exec(self, unit)
					end
					
				end,
				HandlerCode = function (self, unit)
					if not unit:IsDead() then
						EnvEffectTearGasTick(unit, nil, "start turn")
					end
				end,
				param_bindings = false,
			}),
			PlaceObj('MsgReaction', {
				Event = "UnitEndTurn",
				Handler = function (self, unit)
					local reaction_idx = table.find(self.msg_reactions or empty_table, "Event", "UnitEndTurn")
					if not reaction_idx then return end
					
					local function exec(self, unit)
					if not unit:IsDead() then
						EnvEffectTearGasTick(unit, nil, "end turn")
					end
					end
					local id = GetCharacterEffectId(self)
					
					if id then
						if IsKindOf(unit, "StatusEffectObject") and unit:HasStatusEffect(id) then
							exec(self, unit)
						end
					else
						exec(self, unit)
					end
					
				end,
				HandlerCode = function (self, unit)
					if not unit:IsDead() then
						EnvEffectTearGasTick(unit, nil, "end turn")
					end
				end,
				param_bindings = false,
			}),
		},
		'unit_reactions', {
			PlaceObj('UnitReaction', {
				Event = "OnCalcChanceToHit",
				Handler = function (self, target, attacker, action, attack_target, weapon1, weapon2, data)
					if target == attacker then
						local dazed_Cth = {id = "dazed_cth", name = T{"Dazed"}, value = -40}
						table.insert(data.modifiers, dazed_Cth)
						--for _, i in ipairs(data.modifiers) do
							--print("i",i)
						--end
						--print("d", data.modifiers)
						data.mod_add = data.mod_add -40
					end
				end,
				param_bindings = false,
			}),
		},
		'Modifiers', {
			PlaceObj('UnitModifier', {
				mod_add = -60,
				param_bindings = false,
				target_prop = "Explosives",
			}),
		},
		'DisplayName', T(236964331685, --[[ModItemCharacterEffectCompositeDef dazed_flashbang DisplayName]] "Dazed"),
		'Description', T(572612774636, --[[ModItemCharacterEffectCompositeDef dazed_flashbang Description]] "This character has been afflicted by a flashbang. Accuracy is dramatically decreased."),
		'GetDescription', function (self)
			return self.Description
		end,
		'AddEffectText', T(359994604091, --[[ModItemCharacterEffectCompositeDef dazed_flashbang AddEffectText]] "<color EmStyle><DisplayName></color> is dazed"),
		'type', "Debuff",
		'lifetime', "Until End of Turn",
		'Icon', "UI/Hud/Status effects/blinded",
		'RemoveOnEndCombat', true,
		'RemoveOnSatViewTravel', true,
		'RemoveOnCampaignTimeAdvance', true,
		'Shown', true,
		'HasFloatingText', true,
	}),
	PlaceObj('ModItemCode', {
		'name', "SOURCE_CalcBounceParabola_LUA",
		'CodeFileName', "Code/SOURCE_CalcBounceParabola_LUA.lua",
	}),
	PlaceObj('ModItemCode', {
		'name', "SOURCE_AnimGrenadeTraj",
		'CodeFileName', "Code/SOURCE_AnimGrenadeTraj.lua",
	}),
	PlaceObj('ModItemCode', {
		'name', "SOURCE_GrenadeGetAttackResults",
		'CodeFileName', "Code/SOURCE_GrenadeGetAttackResults.lua",
	}),
	PlaceObj('ModItemCode', {
		'name', "SOURCE_ApplyExplosionDamage",
		'CodeFileName', "Code/SOURCE_ApplyExplosionDamage.lua",
	}),
	PlaceObj('ModItemCode', {
		'name', "SOURCE_HeavyWeaponsGetAttackResults",
		'CodeFileName', "Code/SOURCE_HeavyWeaponsGetAttackResults.lua",
	}),
	PlaceObj('ModItemCode', {
		'name', "SOURCE_ThrowableTrapOnLand",
		'CodeFileName', "Code/SOURCE_ThrowableTrapOnLand.lua",
	}),
	PlaceObj('ModItemCode', {
		'name', "SOURCE_GrenadeOnLand",
		'CodeFileName', "Code/SOURCE_GrenadeOnLand.lua",
	}),
	PlaceObj('ModItemCode', {
		'name', "SOURCE_GrenadeMishapChance",
		'CodeFileName', "Code/SOURCE_GrenadeMishapChance.lua",
	}),
	PlaceObj('ModItemCode', {
		'name', "SOURCE_UnitThrowGrenade",
		'CodeFileName', "Code/SOURCE_UnitThrowGrenade.lua",
	}),
	PlaceObj('ModItemCode', {
		'name', "SOURCE_GrenadeGetTrajectory",
		'CodeFileName', "Code/SOURCE_GrenadeGetTrajectory.lua",
	}),
	PlaceObj('ModItemCode', {
		'name', "FUNCTIONS_BounceGrenade",
		'CodeFileName', "Code/FUNCTIONS_BounceGrenade.lua",
	}),
	PlaceObj('ModItemCode', {
		'name', "FUNCTIONS_DeviateGrenade",
		'CodeFileName', "Code/FUNCTIONS_DeviateGrenade.lua",
	}),
	PlaceObj('ModItemCode', {
		'name', "FUNCTIONS_DeviateHeavyWeapons",
		'CodeFileName', "Code/FUNCTIONS_DeviateHeavyWeapons.lua",
	}),
	PlaceObj('ModItemCode', {
		'name', "FUNCTIONS_GrenadeCalcTrajectory",
		'comment', "----------- Includes SOURCE CalcTrajectory function",
		'CodeFileName', "Code/FUNCTIONS_GrenadeCalcTrajectory.lua",
	}),
	PlaceObj('ModItemCode', {
		'name', "FUNCTION_BounceObjMaterialSpeed",
		'CodeFileName', "Code/FUNCTION_BounceObjMaterialSpeed.lua",
	}),
	PlaceObj('ModItemCode', {
		'name', "FUNCTIONS_Debug",
		'CodeFileName', "Code/FUNCTIONS_Debug.lua",
	}),
	PlaceObj('ModItemCode', {
		'name', "FUNCTIONS_Shrapnel",
		'CodeFileName', "Code/FUNCTIONS_Shrapnel.lua",
	}),
	PlaceObj('ModItemCode', {
		'name', "FUNCTIONS_Shrapnel_VectorGenerators",
		'CodeFileName', "Code/FUNCTIONS_Shrapnel_VectorGenerators.lua",
	}),
	PlaceObj('ModItemCode', {
		'name', "FUNCTIONS_Util",
		'CodeFileName', "Code/FUNCTIONS_Util.lua",
	}),
	PlaceObj('ModItemCode', {
		'name', "FUNCTION_ItemChanges",
		'CodeFileName', "Code/FUNCTION_ItemChanges.lua",
	}),
	PlaceObj('ModItemCode', {
		'name', "FUNCTIONS_AIAdjustment",
		'CodeFileName', "Code/FUNCTIONS_AIAdjustment.lua",
	}),
	PlaceObj('ModItemCode', {
		'name', "FUNCTIONS_CombatActions",
		'CodeFileName', "Code/FUNCTIONS_CombatActions.lua",
	}),
	PlaceObj('ModItemCode', {
		'name', "PROPERTIES_Explosives",
		'CodeFileName', "Code/PROPERTIES_Explosives.lua",
	}),
	PlaceObj('ModItemCode', {
		'name', "PROPERTIES_Unit",
		'CodeFileName', "Code/PROPERTIES_Unit.lua",
	}),
	PlaceObj('ModItemCode', {
		'name', "PATCH",
		'CodeFileName', "Code/PATCH.lua",
	}),
	PlaceObj('ModItemCode', {
		'name', "PATCH_call",
		'CodeFileName', "Code/PATCH_call.lua",
	}),
	PlaceObj('ModItemEntity', {
		'name', "nail_can",
		'entity_name', "nail_can",
	}),
	PlaceObj('ModItemEntity', {
		'name', "tear_can",
		'entity_name', "tear_can",
	}),
	PlaceObj('ModItemEntity', {
		'name', "flash_can",
		'entity_name', "flash_can",
	}),
	PlaceObj('ModItemEntity', {
		'name', "smoke_can",
		'entity_name', "smoke_can",
		'material_type', "Tin_Props",
	}),
	PlaceObj('ModItemOptionChoice', {
		'name', "grenade_throw_diff",
		'DisplayName', "Grenade Throw Skill Check Difficulty",
		'Help', "Affects accuracy of thrown grenades. Positive numbers make it harder.",
		'DefaultValue', "Normal (0)",
		'ChoiceList', {
			"-30",
			"Trivial (-25)",
			"-20",
			"-15",
			"Easy (-10)",
			"-5",
			"Normal (0)",
			"5",
			"Hard (10)",
			"15",
			"Very Hard (20)",
			"25",
			"30",
		},
	}),
	PlaceObj('ModItemOptionChoice', {
		'name', "GL_throw_diff",
		'DisplayName', "Grenade Launch Skill Check Difficulty",
		'Help', "Affects accuracy of Grenade Launcher. Positive numbers make it harder.",
		'DefaultValue', "Normal (0)",
		'ChoiceList', {
			"-30",
			"Trivial (-25)",
			"-20",
			"-15",
			"Easy (-10)",
			"-5",
			"Normal (0)",
			"5",
			"Hard (10)",
			"15",
			"Very Hard (20)",
			"25",
			"30",
		},
	}),
	PlaceObj('ModItemOptionChoice', {
		'name', "RPG_throw_diff",
		'DisplayName', "Rocket Launch Skill Check Difficulty",
		'Help', "Affects accuracy of RPG. Positive numbers make it harder.",
		'DefaultValue', "Normal (0)",
		'ChoiceList', {
			"-30",
			"Trivial (-25)",
			"-20",
			"-15",
			"Easy (-10)",
			"-5",
			"Normal (0)",
			"5",
			"Hard (10)",
			"15",
			"Very Hard (20)",
			"25",
			"30",
		},
	}),
	PlaceObj('ModItemOptionToggle', {
		'name', "enabled_bounce",
		'DisplayName', "Enabled Grenade Bouncing",
		'Help', "If enabled, grenades will bounce when colliding with walls, the ground or other objects.",
		'DefaultValue', true,
	}),
	PlaceObj('ModItemOptionToggle', {
		'name', "enabled_bounce_pred",
		'DisplayName', "Enabled Bouncing Prediction",
		'Help', "Will show the bouncing trajectory when targeting. Disable this if facing performance issues, or if you want the extra challenge.",
		'DefaultValue', true,
	}),
	PlaceObj('ModItemOptionChoice', {
		'name', "explosive_dmg",
		'DisplayName', "Explosive Damage Mul %",
		'Help', "Multiplies the explosive damage for all explosives",
		'DefaultValue', "100",
		'ChoiceList', {
			"0",
			"10",
			"20",
			"30",
			"40",
			"50",
			"60",
			"70",
			"80",
			"90",
			"100",
			"110",
			"120",
			"130",
			"140",
			"150",
			"160",
			"170",
			"180",
			"190",
			"200",
		},
	}),
	PlaceObj('ModItemOptionChoice', {
		'name', "shrap_dmg",
		'DisplayName', "Shrapnel Damage Mul %",
		'Help', "Multiplies the shrapnel damage",
		'DefaultValue', "100",
		'ChoiceList', {
			"0",
			"10",
			"20",
			"30",
			"40",
			"50",
			"60",
			"70",
			"80",
			"90",
			"100",
			"110",
			"120",
			"130",
			"140",
			"150",
			"160",
			"170",
			"180",
			"190",
			"200",
		},
	}),
	PlaceObj('ModItemOptionChoice', {
		'name', "ai_deviate_hc",
		'DisplayName', "AI Deviation Skill Roll Handicap Mul %",
		'Help', "By default, AI will have a bonus to its roll for deviation of explosives based on its level. Set this to 0 to disable.",
		'DefaultValue', "100",
		'ChoiceList', {
			"0",
			"10",
			"20",
			"30",
			"40",
			"50",
			"60",
			"70",
			"80",
			"90",
			"100",
			"110",
			"120",
			"130",
			"140",
			"150",
			"160",
			"170",
			"180",
			"190",
			"200",
		},
	}),
	PlaceObj('ModItemOptionChoice', {
		'name', "shrap_num",
		'DisplayName', "Shrapnel Number Mul %",
		'Help', "Multiplies the number of shrapnel spawned. Recommended to leave as default, but you can decrease if facing performance issues. Increase the shrap damage by a similar amount if you do this.",
		'DefaultValue', "100",
		'ChoiceList', {
			"0",
			"10",
			"20",
			"30",
			"40",
			"50",
			"60",
			"70",
			"80",
			"90",
			"100",
			"110",
			"120",
			"130",
			"140",
			"150",
			"160",
			"170",
			"180",
			"190",
			"200",
		},
	}),
	PlaceObj('ModItemOptionChoice', {
		'name', "shrap_eff_chance",
		'DisplayName', "Shrapnel Effect Mul %",
		'Help', "Multiplies the chance of shrapnel causing Bleeding or other status effects related to hitting bodypart.",
		'DefaultValue', "100",
		'ChoiceList', {
			"0",
			"10",
			"20",
			"30",
			"40",
			"50",
			"60",
			"70",
			"80",
			"90",
			"100",
			"110",
			"120",
			"130",
			"140",
			"150",
			"160",
			"170",
			"180",
			"190",
			"200",
		},
	}),
	PlaceObj('ModItemOptionChoice', {
		'name', "deviate_stat",
		'DisplayName', "Throw Accuracy Stat",
		'Help', 'The stat that will determine grenade throwing accuracy. If set to "Dexterity/Explosives", will use the average of these attributes.',
		'DefaultValue', "Dexterity/Explosives",
		'ChoiceList', {
			"Dexterity",
			"Explosives",
			"Dexterity/Explosives",
		},
	}),
	PlaceObj('ModItemOptionChoice', {
		'name', "deviate_stat_GL",
		'DisplayName', "Grenade Launch Accuracy Stat",
		'Help', 'The stat that will determine Grenade Launcher throwing accuracy. If set to "Marksmanship/Explosives", will use the average of these attributes.',
		'DefaultValue', "Marksmanship/Explosives",
		'ChoiceList', {
			"Marksmanship",
			"Explosives",
			"Marksmanship/Explosives",
		},
	}),
	PlaceObj('ModItemOptionChoice', {
		'name', "deviate_stat_RPG",
		'DisplayName', "Rocket Launch Accuracy Stat",
		'Help', 'The stat that will determine RPG accuracy. If set to "Strength/Explosives", will use the average of these attributes.',
		'DefaultValue', "Strength/Explosives",
		'ChoiceList', {
			"Strength",
			"Explosives",
			"Strength/Explosives",
		},
	}),
	PlaceObj('ModItemInventoryItemCompositeDef', {
		'Id', "weapon_shrapnel",
		'object_class', "Pistol",
		'ScrapParts', 6,
		'RepairCost', 70,
		'Reliability', 50,
		'DisplayName', T(214207252979, --[[ModItemInventoryItemCompositeDef weapon_shrapnel DisplayName]] "shrap"),
		'DisplayNamePlural', T(163052994957, --[[ModItemInventoryItemCompositeDef weapon_shrapnel DisplayNamePlural]] "shrap"),
		'UnitStat', "Marksmanship",
		'Cost', 500,
		'CategoryPair', "Handguns",
		'CanAppearStandard', false,
		'Caliber', "9mm",
		'Damage', 10,
		'ObjDamageMod', 50,
		'AimAccuracy', 1,
		'CritChanceScaled', 0,
		'MagazineSize', 15,
		'WeaponRange', 200,
		'PointBlankBonus', 1,
		'OverwatchAngle', 2160,
		'Noise', 10,
		'HolsterSlot', "Leg",
		'AvailableAttacks', {
			"SingleShot",
			"DualShot",
			"CancelShot",
			"MobileShot",
		},
	}),
	PlaceObj('ModItemFolder', {
		'name', "Crafting",
	}, {
		PlaceObj('ModItemCraftOperationsRecipeDef', {
			CraftTime = 10,
			Ingredients = {
				PlaceObj('RecipeIngredient', {
					'item', "Parts",
					'amount', 15,
				}),
				PlaceObj('RecipeIngredient', {
					'item', "BlackPowder",
					'amount', 2,
				}),
			},
			ResultItem = PlaceObj('RecipeIngredient', {
				'item', "NailBomb_IED",
				'amount', 5,
			}),
			group = "Default",
			id = "CraftNailBomb",
		}),
		PlaceObj('ModItemCraftOperationsRecipeDef', {
			CraftTime = 15,
			Ingredients = {
				PlaceObj('RecipeIngredient', {
					'item', "Parts",
					'amount', 15,
				}),
				PlaceObj('RecipeIngredient', {
					'item', "TNT",
					'amount', 3,
				}),
			},
			ResultItem = PlaceObj('RecipeIngredient', {
				'item', "HE_Grenade_1",
				'amount', 5,
			}),
			group = "Default",
			id = "He_grenade_craft_1",
		}),
		PlaceObj('ModItemCraftOperationsRecipeDef', {
			CraftTime = 10,
			Ingredients = {
				PlaceObj('RecipeIngredient', {
					'item', "Parts",
					'amount', 10,
				}),
				PlaceObj('RecipeIngredient', {
					'item', "Meds",
					'amount', 5,
				}),
				PlaceObj('RecipeIngredient', {
					'item', "BlackPowder",
				}),
			},
			ResultItem = PlaceObj('RecipeIngredient', {
				'item', "SmokeGrenade",
				'amount', 5,
			}),
			group = "Default",
			id = "CraftSmokeIED",
		}),
		PlaceObj('ModItemCraftOperationsRecipeDef', {
			CraftTime = 20,
			Ingredients = {
				PlaceObj('RecipeIngredient', {
					'item', "Parts",
					'amount', 10,
				}),
				PlaceObj('RecipeIngredient', {
					'item', "Meds",
					'amount', 15,
				}),
				PlaceObj('RecipeIngredient', {
					'item', "BlackPowder",
				}),
			},
			ResultItem = PlaceObj('RecipeIngredient', {
				'item', "TearGasGrenade",
				'amount', 5,
			}),
			group = "Default",
			id = "CraftTearGasIED",
		}),
		PlaceObj('ModItemCraftOperationsRecipeDef', {
			CraftTime = 2,
			Ingredients = {
				PlaceObj('RecipeIngredient', {
					'item', "Parts",
					'amount', 10,
				}),
				PlaceObj('RecipeIngredient', {
					'item', "BlackPowder",
					'amount', 5,
				}),
			},
			ResultItem = PlaceObj('RecipeIngredient', {
				'item', "Pipe_IED",
				'amount', 5,
			}),
			group = "Default",
			id = "CraftPipeBombShortFuse",
		}),
		PlaceObj('ModItemCraftOperationsRecipeDef', {
			CraftTime = 10,
			Ingredients = {
				PlaceObj('RecipeIngredient', {
					'item', "Parts",
					'amount', 10,
				}),
				PlaceObj('RecipeIngredient', {
					'item', "BlackPowder",
					'amount', 2,
				}),
			},
			ResultItem = PlaceObj('RecipeIngredient', {
				'item', "ConcussiveGrenade",
				'amount', 5,
			}),
			group = "Default",
			id = "CraftFlashbangIED",
		}),
		}),
	PlaceObj('ModItemFolder', {
		'name', "FXs",
	}, {
		PlaceObj('ModItemCode', {
			'name', "FX_Inherit",
			'CodeFileName', "Code/FX_Inherit.lua",
		}),
		PlaceObj('ModItemCode', {
			'name', "PlaceObj_FX",
			'CodeFileName', "Code/PlaceObj_FX.lua",
		}),
		PlaceObj('ModItemFolder', {
			'name', "Pipe",
		}, {
			PlaceObj('ModItemActionFXObject', {
				Action = "Spawn",
				Actor = "Pipe_IED",
				Attach = true,
				ColorModifier = 4284769380,
				Delay = 100,
				DetailLevel = 100,
				GameTime = true,
				Moment = "start",
				Object = "Weapon_PipeBomb",
				OffsetDir = "ActionDir",
				group = "Explosion - Grenade - Pipe Bomb VFX",
				handle = "K8Qy_JDY",
				id = "mwoiOav_",
			}),
			}),
		PlaceObj('ModItemFolder', {
			'name', "Cylinder",
		}, {
			PlaceObj('ModItemActionFXObject', {
				Action = "Spawn",
				Actor = "IncendiaryGrenade",
				Attach = true,
				ColorModifier = 4289795598,
				Delay = 100,
				DetailLevel = 100,
				GameTime = true,
				Moment = "start",
				Object = "Weapon_IncendiaryGrenade",
				OffsetDir = "ActionDir",
				group = "Explosion - Grenade - Pipe Bomb VFX",
				handle = "K8Qy_JDY",
				id = "3YQdpAfz",
			}),
			PlaceObj('ModItemActionFXObject', {
				Action = "Spawn",
				Actor = "HE_Grenade_1",
				Attach = true,
				Delay = 100,
				DetailLevel = 100,
				Moment = "start",
				Object = "Weapon_SmokeGrenade",
				Scale = 90,
				group = "Default",
				handle = "K8Qy_JDY",
				id = "K8Qy_JDY",
			}),
			}),
		PlaceObj('ModItemFolder', {
			'name', "Stick",
		}, {
			PlaceObj('ModItemActionFXParticles', {
				Action = "Spawn",
				Actor = "Weapon_TNT",
				Attach = true,
				BehaviorMoment = "end",
				Moment = "start",
				OffsetDir = "SpotY",
				Particles = "Weapon_PipeBomb_Fuse",
				Spot = "Particle",
				group = "Default",
				handle = "NzCxQfx-",
				id = "EkRCa1g6",
			}),
			PlaceObj('ModItemActionFXObject', {
				Action = "Spawn",
				Actor = "TNTBolt_IED",
				Attach = true,
				ColorModifier = 4289805326,
				Delay = 100,
				DetailLevel = 100,
				GameTime = true,
				Moment = "start",
				Object = "Weapon_TNT",
				OffsetDir = "ActionDir",
				group = "Explosion - Grenade - Pipe Bomb VFX",
				handle = "K8Qy_JDY",
				id = "bBo7O2vQ",
			}),
			}),
		PlaceObj('ModItemFolder', {
			'name', "Jar",
		}),
		PlaceObj('ModItemFolder', {
			'name', "Can",
		}, {
			PlaceObj('ModItemActionFXObject', {
				Action = "Spawn",
				Actor = "ConcussiveGrenade_IED",
				Attach = true,
				Delay = 100,
				DetailLevel = 100,
				GameTime = true,
				Moment = "start",
				Object = "Weapon_FlashCanIED",
				OffsetDir = "ActionDir",
				group = "Explosion - Grenade - Pipe Bomb VFX",
				handle = "K8Qy_JDY",
				id = "YmH6IxkH",
			}),
			PlaceObj('ModItemActionFXParticles', {
				Action = "Spawn",
				Actor = "Weapon_CanIED",
				Attach = true,
				BehaviorMoment = "end",
				Moment = "start",
				Offset = point(0, 0, 150),
				OffsetDir = "SpotY",
				Particles = "Weapon_PipeBomb_Fuse",
				Scale = 80,
				Spot = "Particle",
				group = "Default",
				handle = "NzCxQfx-",
				id = "NzCxQfx-",
			}),
			PlaceObj('ModItemActionFXParticles', {
				Action = "Spawn",
				Actor = "Weapon_FlashCanIED",
				Attach = true,
				BehaviorMoment = "end",
				Moment = "start",
				Offset = point(0, 0, 250),
				OffsetDir = "SpotY",
				Particles = "Weapon_PipeBomb_Fuse",
				Scale = 80,
				Spot = "Particle",
				group = "Explosion - Grenade - Pipe Bomb VFX",
				handle = "NzCxQfx-",
				id = "tFubTyTu",
			}),
			PlaceObj('ModItemActionFXParticles', {
				Action = "Spawn",
				Actor = "Weapon_NailCanIED",
				Attach = true,
				BehaviorMoment = "end",
				Moment = "start",
				Offset = point(0, 0, 150),
				OffsetDir = "SpotY",
				Particles = "Weapon_PipeBomb_Fuse",
				Scale = 80,
				Spot = "Particle",
				group = "Explosion - Grenade - Pipe Bomb VFX",
				handle = "NzCxQfx-",
				id = "R-7C51GE",
			}),
			PlaceObj('ModItemActionFXObject', {
				Action = "Spawn",
				Actor = "NailBomb_IED",
				Attach = true,
				ColorModifier = 87308093,
				Delay = 100,
				DetailLevel = 100,
				EditableColor1 = 4281612093,
				EditableColor2 = 4281612093,
				EditableColor3 = 4286742648,
				EditableMetallic3 = 53,
				EditableRoughness1 = 127,
				EditableRoughness2 = 127,
				EditableRoughness3 = 127,
				GameTime = true,
				Moment = "start",
				Object = "Weapon_NailCanIED",
				Offset = point(1, -1, 0),
				OffsetDir = "ActionDir",
				Scale = 120,
				group = "Explosion - Grenade - Pipe Bomb VFX",
				handle = "K8Qy_JDY",
				id = "uvI7IVhL",
			}),
			PlaceObj('ModItemActionFXObject', {
				Action = "Spawn",
				Actor = "SmokeGrenade_IED",
				Attach = true,
				ColorModifier = 87308093,
				Delay = 100,
				DetailLevel = 100,
				EditableColor1 = 4281612093,
				EditableColor2 = 4281612093,
				EditableColor3 = 4286742648,
				EditableMetallic3 = 53,
				EditableRoughness1 = 127,
				EditableRoughness2 = 127,
				EditableRoughness3 = 127,
				GameTime = true,
				Moment = "start",
				Object = "Weapon_SmokeCanIED",
				Offset = point(1, -1, 0),
				OffsetDir = "ActionDir",
				Scale = 125,
				group = "Explosion - Grenade - Pipe Bomb VFX",
				handle = "K8Qy_JDY",
				id = "l0V-TW9J",
			}),
			PlaceObj('ModItemActionFXObject', {
				Action = "Spawn",
				Actor = "TearGasGrenade_IED",
				Attach = true,
				ColorModifier = 87308093,
				Delay = 100,
				DetailLevel = 100,
				EditableColor1 = 4281612093,
				EditableColor2 = 4281612093,
				EditableColor3 = 4286742648,
				EditableMetallic3 = 53,
				EditableRoughness1 = 127,
				EditableRoughness2 = 127,
				EditableRoughness3 = 127,
				GameTime = true,
				Moment = "start",
				Object = "Weapon_TearCanIED",
				Offset = point(1, -1, 0),
				OffsetDir = "ActionDir",
				Scale = 125,
				group = "Explosion - Grenade - Pipe Bomb VFX",
				handle = "K8Qy_JDY",
				id = "Gopwg9SS",
			}),
			}),
		PlaceObj('ModItemFolder', {
			'name', "Can_on_ground",
		}, {
			PlaceObj('ModItemActionFXObject', {
				Actor = "SmokeGrenadeSpinner",
				Attach = true,
				Moment = "start",
				Object = "smoke_can",
				Offset = point(0, 0, 50),
				Orientation = "RotateByPresetAngle",
				PresetOrientationAngle = 90,
				Scale = 125,
				Source = "ActorParent",
				group = "Explosion - Grenade - Pipe Bomb VFX",
				handle = "QTMDxdo6",
				id = "QTMDxdo6",
			}),
			}),
		PlaceObj('ModItemActionFXParticles', {
			Action = "Spawn",
			Actor = "Weapon_MolotovCocktail",
			Attach = true,
			BehaviorMoment = "end",
			Flags = "LockedOrientation",
			Moment = "start",
			Particles = "Molotov_Fire1x1",
			PresetOrientationAngle = -1,
			Scale = 9,
			SingleAttach = true,
			Spot = "Particle",
			UseActorColorModifier = true,
			group = "Default",
			handle = "NzCxQfx-",
			id = "ORWlPyss",
		}),
		}),
	PlaceObj('ModItemFolder', {
		'name', "Explosives",
	}, {
		PlaceObj('ModItemFolder', {
			'name', "Material",
		}, {
			PlaceObj('ModItemInventoryItemCompositeDef', {
				'Group', "Grenade - Component",
				'Id', "PETN",
				'object_class', "ExplosiveSubstance",
				'ScrapParts', 5,
				'Repairable', false,
				'Icon', "UI/Icons/Items/petn",
				'DisplayName', T(619953478508, --[[ModItemInventoryItemCompositeDef PETN DisplayName]] "PETN"),
				'DisplayNamePlural', T(166918087108, --[[ModItemInventoryItemCompositeDef PETN DisplayNamePlural]] "PETN"),
				'Description', T(172653806478, --[[ModItemInventoryItemCompositeDef PETN Description]] "A powerful plastic explosive substance used in major demolition and military high-grade explosives."),
				'AdditionalHint', T(195587387816, --[[ModItemInventoryItemCompositeDef PETN AdditionalHint]] "<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Combine with a Detonator type to create an Explosive"),
				'UnitStat', "Explosives",
				'Cost', 500,
				'CanAppearInShop', true,
				'Tier', 3,
				'RestockWeight', 35,
				'CategoryPair', "Components",
				'CenterUnitDamageMod', 130,
				'CenterObjDamageMod', 500,
				'AreaOfEffect', 4,
				'AreaObjDamageMod', 500,
				'DeathType', "BlowUp",
				'BaseDamage', 55,
			}),
			PlaceObj('ModItemInventoryItemCompositeDef', {
				'Group', "Grenade - Component",
				'Id', "C4",
				'object_class', "ExplosiveSubstance",
				'Repairable', false,
				'Icon', "UI/Icons/Items/c4",
				'DisplayName', T(751572443745, --[[ModItemInventoryItemCompositeDef C4 DisplayName]] "C4"),
				'DisplayNamePlural', T(867951071563, --[[ModItemInventoryItemCompositeDef C4 DisplayNamePlural]] "C4"),
				'AdditionalHint', T(995022991672, --[[ModItemInventoryItemCompositeDef C4 AdditionalHint]] "<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Combine with a Detonator to create an explosive"),
				'UnitStat', "Explosives",
				'Cost', 400,
				'CanAppearInShop', true,
				'Tier', 2,
				'RestockWeight', 35,
				'CategoryPair', "Components",
				'CenterUnitDamageMod', 130,
				'CenterObjDamageMod', 500,
				'AreaOfEffect', 2,
				'AreaObjDamageMod', 500,
				'DeathType', "BlowUp",
				'BaseDamage', 38,
				'Noise', 30,
			}),
			PlaceObj('ModItemInventoryItemCompositeDef', {
				'Group', "Grenade - Component",
				'Id', "BlackPowder",
				'object_class', "ExplosiveSubstance",
				'Repairable', false,
				'Icon', "UI/Icons/Items/black_powder",
				'DisplayName', T(714362259251, --[[ModItemInventoryItemCompositeDef BlackPowder DisplayName]] "Gunpowder"),
				'DisplayNamePlural', T(161274261102, --[[ModItemInventoryItemCompositeDef BlackPowder DisplayNamePlural]] "Gunpowder"),
				'AdditionalHint', T(515164545390, --[[ModItemInventoryItemCompositeDef BlackPowder AdditionalHint]] "<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Used in Craft Ammo and Craft Explosives operations"),
				'UnitStat', "Explosives",
				'Cost', 400,
				'CanAppearInShop', true,
				'MaxStock', 10,
				'CategoryPair', "Components",
				'ShopStackSize', 5,
				'CenterUnitDamageMod', 130,
				'CenterObjDamageMod', 200,
				'AreaOfEffect', 4,
				'AreaObjDamageMod', 200,
				'PenetrationClass', 4,
				'BurnGround', false,
				'DeathType', "BlowUp",
				'BaseDamage', 33,
			}),
			PlaceObj('ModItemInventoryItemCompositeDef', {
				'Group', "Grenade - Component",
				'Id', "TNT",
				'object_class', "ExplosiveSubstance",
				'Repairable', false,
				'Icon', "UI/Icons/Items/tnt",
				'DisplayName', T(464151031897, --[[ModItemInventoryItemCompositeDef TNT DisplayName]] "TNT"),
				'DisplayNamePlural', T(897946100206, --[[ModItemInventoryItemCompositeDef TNT DisplayNamePlural]] "TNT"),
				'Description', T(579110878277, --[[ModItemInventoryItemCompositeDef TNT Description]] "The go-to tool of railroad builders and Wild West moustache villains, the TNT is easy to find, use and abuse."),
				'AdditionalHint', T(728674085231, --[[ModItemInventoryItemCompositeDef TNT AdditionalHint]] "<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Combine with a Detonator type to create an Explosive\n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Larger blast area"),
				'UnitStat', "Explosives",
				'Cost', 200,
				'CanAppearInShop', true,
				'MaxStock', 2,
				'RestockWeight', 60,
				'CategoryPair', "Components",
				'CenterUnitDamageMod', 130,
				'CenterObjDamageMod', 300,
				'AreaOfEffect', 5,
				'AreaObjDamageMod', 300,
				'PenetrationClass', 4,
				'DeathType', "BlowUp",
				'BaseDamage', 38,
				'Noise', 30,
			}),
			}),
		PlaceObj('ModItemFolder', {
			'name', "ThrowableTrap",
		}, {
			PlaceObj('ModItemInventoryItemCompositeDef', {
				'Group', "Grenade - Explosive",
				'Id', "ProximityC4",
				'object_class', "ThrowableTrapItem",
				'Repairable', false,
				'Reliability', 100,
				'Icon', "UI/Icons/Items/proximity_c4",
				'ItemType', "Grenade",
				'DisplayName', T(601916796881, --[[ModItemInventoryItemCompositeDef ProximityC4 DisplayName]] "Proximity C4"),
				'DisplayNamePlural', T(749835210949, --[[ModItemInventoryItemCompositeDef ProximityC4 DisplayNamePlural]] "Proximity C4"),
				'AdditionalHint', T(252361188007, --[[ModItemInventoryItemCompositeDef ProximityC4 AdditionalHint]] "<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Explodes when an enemy enters a small area around it"),
				'UnitStat', "Explosives",
				'Cost', 1200,
				'CanAppearInShop', true,
				'Tier', 2,
				'MaxStock', 1,
				'RestockWeight', 10,
				'CategoryPair', "Grenade",
				'MinMishapChance', -2,
				'MaxMishapChance', 18,
				'MaxMishapRange', 6,
				'Scatter', 2,
				'AttackAP', 7000,
				'BaseRange', 3,
				'ThrowMaxRange', 8,
				'CanBounce', false,
				'IgnoreCoverReduction', 1,
				'Noise', 30,
				'Entity', "Explosive_C4",
				'ActionIcon', "UI/Icons/Hud/throw_proximity_explosive",
				'r_mass', 2000,
				'r_shape', "Brick",
				'r_shrap_num', 200,
				'TriggerType', "Proximity",
				'ExplosiveType', "C4",
			}),
			PlaceObj('ModItemInventoryItemCompositeDef', {
				'Group', "Grenade - Explosive",
				'Id', "ProximityPETN",
				'object_class', "ThrowableTrapItem",
				'Repairable', false,
				'Reliability', 100,
				'Icon', "UI/Icons/Items/proximity_petn",
				'ItemType', "Grenade",
				'DisplayName', T(330241233338, --[[ModItemInventoryItemCompositeDef ProximityPETN DisplayName]] "Proximity PETN"),
				'DisplayNamePlural', T(182079965364, --[[ModItemInventoryItemCompositeDef ProximityPETN DisplayNamePlural]] "Proximity PETN"),
				'AdditionalHint', T(220972891844, --[[ModItemInventoryItemCompositeDef ProximityPETN AdditionalHint]] "<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Explodes when an enemy enters a small area around it"),
				'UnitStat', "Explosives",
				'Cost', 1500,
				'CanAppearInShop', true,
				'Tier', 3,
				'MaxStock', 1,
				'RestockWeight', 10,
				'CategoryPair', "Grenade",
				'MinMishapChance', -2,
				'MaxMishapChance', 18,
				'MaxMishapRange', 6,
				'AttackAP', 7000,
				'BaseRange', 3,
				'ThrowMaxRange', 8,
				'CanBounce', false,
				'Noise', 30,
				'Entity', "Explosive_PETN",
				'ActionIcon', "UI/Icons/Hud/throw_proximity_explosive",
				'r_mass', 1800,
				'r_shape', "Brick",
				'r_shrap_num', 200,
				'TriggerType', "Proximity",
				'ExplosiveType', "PETN",
			}),
			PlaceObj('ModItemInventoryItemCompositeDef', {
				'Group', "Grenade - Explosive",
				'Id', "ProximityTNT",
				'object_class', "ThrowableTrapItem",
				'Repairable', false,
				'Reliability', 100,
				'Icon', "UI/Icons/Items/proximity_tnt",
				'ItemType', "Grenade",
				'DisplayName', T(367750793000, --[[ModItemInventoryItemCompositeDef ProximityTNT DisplayName]] "Proximity TNT"),
				'DisplayNamePlural', T(977084522969, --[[ModItemInventoryItemCompositeDef ProximityTNT DisplayNamePlural]] "Proximity TNT"),
				'AdditionalHint', T(222949275095, --[[ModItemInventoryItemCompositeDef ProximityTNT AdditionalHint]] "<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Explodes when an enemy enters a small area around it\n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> High mishap chance"),
				'UnitStat', "Explosives",
				'Cost', 850,
				'CanAppearInShop', true,
				'Tier', 2,
				'MaxStock', 1,
				'RestockWeight', 20,
				'MinMishapChance', 2,
				'MaxMishapChance', 30,
				'MaxMishapRange', 6,
				'AttackAP', 7000,
				'BaseRange', 3,
				'ThrowMaxRange', 7,
				'CanBounce', false,
				'Noise', 30,
				'Entity', "Explosive_TNT",
				'ActionIcon', "UI/Icons/Hud/throw_proximity_explosive",
				'r_mass', 1500,
				'r_shape', "Long",
				'r_shrap_num', 200,
				'TriggerType', "Proximity",
			}),
			PlaceObj('ModItemInventoryItemCompositeDef', {
				'Group', "Grenade - Explosive",
				'Id', "TimedC4",
				'object_class', "ThrowableTrapItem",
				'Repairable', false,
				'Reliability', 100,
				'Icon', "UI/Icons/Items/timed_c4",
				'ItemType', "Grenade",
				'DisplayName', T(559267717229, --[[ModItemInventoryItemCompositeDef TimedC4 DisplayName]] "Timed C4"),
				'DisplayNamePlural', T(434330146200, --[[ModItemInventoryItemCompositeDef TimedC4 DisplayNamePlural]] "Timed C4"),
				'AdditionalHint', T(528995647980, --[[ModItemInventoryItemCompositeDef TimedC4 AdditionalHint]] "<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Explodes after 1 turn (or 5 seconds out of combat)"),
				'UnitStat', "Explosives",
				'Cost', 1200,
				'CanAppearInShop', true,
				'Tier', 2,
				'MaxStock', 1,
				'RestockWeight', 10,
				'CategoryPair', "Grenade",
				'MinMishapChance', -2,
				'MaxMishapChance', 18,
				'MinMishapRange', 0,
				'MaxMishapRange', 3,
				'AttackAP', 4000,
				'BaseRange', 3,
				'ThrowMaxRange', 12,
				'CanBounce', false,
				'InaccurateMaxOffset', 4000,
				'IgnoreCoverReduction', 1,
				'Noise', 30,
				'Entity', "Explosive_C4",
				'ActionIcon', "UI/Icons/Hud/throw_timed_explosives",
				'r_mass', 2000,
				'r_shape', "Brick",
				'r_shrap_num', 200,
				'TriggerType', "Timed",
				'ExplosiveType', "C4",
			}),
			PlaceObj('ModItemInventoryItemCompositeDef', {
				'Group', "Grenade - Explosive",
				'Id', "TimedPETN",
				'object_class', "ThrowableTrapItem",
				'Repairable', false,
				'Reliability', 100,
				'Icon', "UI/Icons/Items/timed_petn",
				'ItemType', "Grenade",
				'DisplayName', T(371795015084, --[[ModItemInventoryItemCompositeDef TimedPETN DisplayName]] "Timed PETN"),
				'DisplayNamePlural', T(922603486603, --[[ModItemInventoryItemCompositeDef TimedPETN DisplayNamePlural]] "Timed PETN"),
				'AdditionalHint', T(200584217333, --[[ModItemInventoryItemCompositeDef TimedPETN AdditionalHint]] "<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Explodes after 1 turn (or 5 seconds out of combat)"),
				'UnitStat', "Explosives",
				'Cost', 1500,
				'CanAppearInShop', true,
				'Tier', 3,
				'MaxStock', 1,
				'RestockWeight', 10,
				'CategoryPair', "Grenade",
				'MinMishapChance', -2,
				'MaxMishapChance', 18,
				'MinMishapRange', 0,
				'MaxMishapRange', 3,
				'AttackAP', 4000,
				'BaseRange', 3,
				'ThrowMaxRange', 12,
				'CanBounce', false,
				'InaccurateMaxOffset', 4000,
				'Noise', 30,
				'Entity', "Explosive_PETN",
				'ActionIcon', "UI/Icons/Hud/throw_timed_explosives",
				'r_mass', 1800,
				'r_shape', "Brick",
				'r_shrap_num', 200,
				'TriggerType', "Timed",
				'ExplosiveType', "PETN",
			}),
			PlaceObj('ModItemInventoryItemCompositeDef', {
				'Group', "Grenade - Explosive",
				'Id', "TimedTNT",
				'object_class', "ThrowableTrapItem",
				'Repairable', false,
				'Reliability', 100,
				'Icon', "UI/Icons/Items/timed_tnt",
				'ItemType', "Grenade",
				'DisplayName', T(533173120854, --[[ModItemInventoryItemCompositeDef TimedTNT DisplayName]] "Timed TNT"),
				'DisplayNamePlural', T(818362435719, --[[ModItemInventoryItemCompositeDef TimedTNT DisplayNamePlural]] "Timed TNT"),
				'AdditionalHint', T(123704050861, --[[ModItemInventoryItemCompositeDef TimedTNT AdditionalHint]] "<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Explodes after 1 turn (or 5 seconds out of combat)\n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> High mishap chance"),
				'UnitStat', "Explosives",
				'Cost', 850,
				'CanAppearInShop', true,
				'Tier', 2,
				'MaxStock', 1,
				'RestockWeight', 20,
				'CategoryPair', "Grenade",
				'MinMishapChance', 2,
				'MaxMishapChance', 30,
				'MinMishapRange', 0,
				'MaxMishapRange', 3,
				'AttackAP', 4000,
				'BaseRange', 3,
				'ThrowMaxRange', 12,
				'CanBounce', false,
				'InaccurateMaxOffset', 4000,
				'Noise', 30,
				'Entity', "Explosive_TNT",
				'ActionIcon', "UI/Icons/Hud/throw_timed_explosives",
				'r_mass', 1500,
				'r_shape', "Long",
				'r_shrap_num', 200,
				'TriggerType', "Timed",
			}),
			PlaceObj('ModItemInventoryItemCompositeDef', {
				'Group', "Grenade - Explosive",
				'Id', "RemoteC4",
				'object_class', "ThrowableTrapItem",
				'Repairable', false,
				'Reliability', 100,
				'Icon', "UI/Icons/Items/remote_c4",
				'ItemType', "Grenade",
				'DisplayName', T(334869422725, --[[ModItemInventoryItemCompositeDef RemoteC4 DisplayName]] "Remote C4"),
				'DisplayNamePlural', T(811274447352, --[[ModItemInventoryItemCompositeDef RemoteC4 DisplayNamePlural]] "Remote C4"),
				'AdditionalHint', T(742264656324, --[[ModItemInventoryItemCompositeDef RemoteC4 AdditionalHint]] "<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Explodes when triggered by a remote Detonator switch"),
				'UnitStat', "Explosives",
				'Cost', 800,
				'CanAppearInShop', true,
				'Tier', 2,
				'MaxStock', 1,
				'RestockWeight', 10,
				'CategoryPair', "Grenade",
				'MinMishapChance', -2,
				'MaxMishapChance', 18,
				'MaxMishapRange', 6,
				'AttackAP', 4000,
				'BaseRange', 4,
				'ThrowMaxRange', 14,
				'IgnoreCoverReduction', 1,
				'Noise', 30,
				'Entity', "Explosive_C4",
				'ActionIcon', "UI/Icons/Hud/throw_remote_explosive",
				'r_mass', 2000,
				'r_shape', "Brick",
				'r_soft_surface', true,
				'r_shrap_num', 200,
				'TriggerType', "Remote",
				'ExplosiveType', "C4",
			}),
			PlaceObj('ModItemInventoryItemCompositeDef', {
				'Group', "Grenade - Explosive",
				'Id', "RemotePETN",
				'object_class', "ThrowableTrapItem",
				'Repairable', false,
				'Reliability', 100,
				'Icon', "UI/Icons/Items/remote_petn",
				'ItemType', "Grenade",
				'DisplayName', T(706074896022, --[[ModItemInventoryItemCompositeDef RemotePETN DisplayName]] "Remote PETN"),
				'DisplayNamePlural', T(637241516535, --[[ModItemInventoryItemCompositeDef RemotePETN DisplayNamePlural]] "Remote PETN"),
				'AdditionalHint', T(531287541505, --[[ModItemInventoryItemCompositeDef RemotePETN AdditionalHint]] "<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Explodes when triggered by a remote Detonator switch"),
				'UnitStat', "Explosives",
				'Cost', 800,
				'CanAppearInShop', true,
				'Tier', 3,
				'MaxStock', 1,
				'RestockWeight', 10,
				'CategoryPair', "Grenade",
				'MinMishapChance', -2,
				'MaxMishapChance', 18,
				'MaxMishapRange', 6,
				'AttackAP', 4000,
				'BaseRange', 3,
				'ThrowMaxRange', 12,
				'CanBounce', false,
				'Noise', 30,
				'Entity', "Explosive_PETN",
				'ActionIcon', "UI/Icons/Hud/throw_remote_explosive",
				'r_mass', 1800,
				'r_shape', "Brick",
				'r_shrap_num', 200,
				'TriggerType', "Remote",
				'ExplosiveType', "PETN",
			}),
			PlaceObj('ModItemInventoryItemCompositeDef', {
				'Group', "Grenade - Explosive",
				'Id', "RemoteTNT",
				'object_class', "ThrowableTrapItem",
				'Repairable', false,
				'Reliability', 100,
				'Icon', "UI/Icons/Items/remote_tnt",
				'ItemType', "Grenade",
				'DisplayName', T(983794362389, --[[ModItemInventoryItemCompositeDef RemoteTNT DisplayName]] "Remote TNT"),
				'DisplayNamePlural', T(396317563366, --[[ModItemInventoryItemCompositeDef RemoteTNT DisplayNamePlural]] "Remote TNT"),
				'AdditionalHint', T(174894704271, --[[ModItemInventoryItemCompositeDef RemoteTNT AdditionalHint]] "<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Explodes when triggered by a remote Detonator switch\n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> High mishap chance"),
				'UnitStat', "Explosives",
				'Cost', 600,
				'CanAppearInShop', true,
				'Tier', 2,
				'MaxStock', 1,
				'RestockWeight', 10,
				'CategoryPair', "Grenade",
				'MinMishapChance', 2,
				'MaxMishapChance', 30,
				'MaxMishapRange', 6,
				'AttackAP', 4000,
				'BaseRange', 3,
				'ThrowMaxRange', 12,
				'CanBounce', false,
				'Noise', 30,
				'Entity', "Explosive_TNT",
				'ActionIcon', "UI/Icons/Hud/throw_remote_explosive",
				'r_mass', 1500,
				'r_shape', "Long",
				'r_shrap_num', 200,
				'TriggerType', "Remote",
			}),
			}),
		PlaceObj('ModItemFolder', {
			'name', "Ordnance",
		}, {
			PlaceObj('ModItemInventoryItemCompositeDef', {
				'Group', "Ammo - Ordnance",
				'Id', "_40mmFragGrenade",
				'object_class', "Ordnance",
				'Icon', "UI/Icons/Items/40mm_frag_grenade",
				'DisplayName', T(379883134750, --[[ModItemInventoryItemCompositeDef _40mmFragGrenade DisplayName]] "40 mm HE"),
				'DisplayNamePlural', T(448697893920, --[[ModItemInventoryItemCompositeDef _40mmFragGrenade DisplayNamePlural]] "40 mm HE"),
				'Description', T(429484513685, --[[ModItemInventoryItemCompositeDef _40mmFragGrenade Description]] "40 mm ordnance ammo for Grenade Launchers."),
				'AdditionalHint', T(926889899942, --[[ModItemInventoryItemCompositeDef _40mmFragGrenade AdditionalHint]] "<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Inflicts <color EmStyle>Bleeding</color> in the epicenter"),
				'Cost', 300,
				'CanAppearInShop', true,
				'Tier', 2,
				'MaxStock', 5,
				'RestockWeight', 50,
				'CategoryPair', "Ordnance",
				'CenterUnitDamageMod', 130,
				'CenterObjDamageMod', 500,
				'AreaObjDamageMod', 500,
				'PenetrationClass', 4,
				'DeathType', "BlowUp",
				'Caliber', "40mmGrenade",
				'BaseDamage', 40,
				'Entity', "Weapon_MilkorMGL_Shell",
				'r_shrap_num', 300,
			}),
			PlaceObj('ModItemInventoryItemCompositeDef', {
				'Group', "Ammo - Ordnance",
				'Id', "Warhead_Frag",
				'object_class', "Ordnance",
				'Icon', "UI/Icons/Items/warhead_frag",
				'DisplayName', T(496295170204, --[[ModItemInventoryItemCompositeDef Warhead_Frag DisplayName]] "HE Rocket"),
				'DisplayNamePlural', T(479516392578, --[[ModItemInventoryItemCompositeDef Warhead_Frag DisplayNamePlural]] "HE Rockets"),
				'Description', T(906581367082, --[[ModItemInventoryItemCompositeDef Warhead_Frag Description]] "Ordnance ammo for Rocket Launchers."),
				'AdditionalHint', T(209111451522, --[[ModItemInventoryItemCompositeDef Warhead_Frag AdditionalHint]] "<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Inflicts Suppressed in the epicenter"),
				'Cost', 400,
				'CanAppearInShop', true,
				'Tier', 3,
				'MaxStock', 5,
				'RestockWeight', 50,
				'CategoryPair', "Ordnance",
				'CenterUnitDamageMod', 130,
				'CenterObjDamageMod', 500,
				'AreaOfEffect', 4,
				'AreaObjDamageMod', 500,
				'DeathType', "BlowUp",
				'Caliber', "Warhead",
				'BaseDamage', 50,
				'Noise', 30,
				'r_shrap_num', 300,
			}),
			PlaceObj('ModItemInventoryItemCompositeDef', {
				'Group', "Ammo - Ordnance",
				'Id', "MortarShell_Gas",
				'object_class', "Ordnance",
				'RepairCost', 0,
				'Repairable', false,
				'Reliability', 100,
				'Icon', "UI/Icons/Items/mortar_shell_gas",
				'DisplayName', T(533793585299, --[[ModItemInventoryItemCompositeDef MortarShell_Gas DisplayName]] "Mortar Gas Cartridge"),
				'DisplayNamePlural', T(568374576075, --[[ModItemInventoryItemCompositeDef MortarShell_Gas DisplayNamePlural]] "Mortar Gas Cartridges"),
				'Description', T(692883813791, --[[ModItemInventoryItemCompositeDef MortarShell_Gas Description]] "Ordnance ammo for Mortars."),
				'AdditionalHint', T(481066088983, --[[ModItemInventoryItemCompositeDef MortarShell_Gas AdditionalHint]] "<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Inflicts <color EmStyle>Choking</color>\n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Ranged attacks passing through gas become Grazing hits\n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Almost silent"),
				'Cost', 400,
				'CanAppearInShop', true,
				'Tier', 2,
				'MaxStock', 5,
				'RestockWeight', 25,
				'CategoryPair', "Ordnance",
				'PenetrationClass', 1,
				'BurnGround', false,
				'Caliber', "MortarShell",
				'BaseDamage', 0,
				'Noise', 0,
				'aoeType', "toxicgas",
			}),
			PlaceObj('ModItemInventoryItemCompositeDef', {
				'Group', "Ammo - Ordnance",
				'Id', "MortarShell_HE",
				'object_class', "Ordnance",
				'RepairCost', 0,
				'Repairable', false,
				'Reliability', 100,
				'Icon', "UI/Icons/Items/mortar_shell_he",
				'DisplayName', T(314888807427, --[[ModItemInventoryItemCompositeDef MortarShell_HE DisplayName]] "Mortar Cartridge"),
				'DisplayNamePlural', T(610141949220, --[[ModItemInventoryItemCompositeDef MortarShell_HE DisplayNamePlural]] "Mortar Cartridges"),
				'Description', T(134585683801, --[[ModItemInventoryItemCompositeDef MortarShell_HE Description]] "Explosive Ordnance ammo for Mortars."),
				'Cost', 300,
				'CanAppearInShop', true,
				'Tier', 2,
				'MaxStock', 5,
				'RestockWeight', 50,
				'CategoryPair', "Ordnance",
				'CenterObjDamageMod', 500,
				'AreaOfEffect', 5,
				'AreaObjDamageMod', 500,
				'PenetrationClass', 4,
				'DeathType', "BlowUp",
				'Caliber', "MortarShell",
				'BaseDamage', 40,
			}),
			PlaceObj('ModItemInventoryItemCompositeDef', {
				'Group', "Ammo - Ordnance",
				'Id', "MortarShell_Smoke",
				'object_class', "Ordnance",
				'RepairCost', 0,
				'Repairable', false,
				'Reliability', 100,
				'Icon', "UI/Icons/Items/mortar_shell_smoke",
				'DisplayName', T(377318516720, --[[ModItemInventoryItemCompositeDef MortarShell_Smoke DisplayName]] "Mortar Smoke Cartridge"),
				'DisplayNamePlural', T(191255251161, --[[ModItemInventoryItemCompositeDef MortarShell_Smoke DisplayNamePlural]] "Mortar Smoke Cartridges"),
				'Description', T(322194031802, --[[ModItemInventoryItemCompositeDef MortarShell_Smoke Description]] "Ordnance ammo for Mortars."),
				'AdditionalHint', T(835706114170, --[[ModItemInventoryItemCompositeDef MortarShell_Smoke AdditionalHint]] "<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Ranged attacks passing through gas become <color EmStyle>grazing</color> hits\n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> No damage\n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Almost silent"),
				'Cost', 400,
				'CanAppearInShop', true,
				'Tier', 2,
				'MaxStock', 5,
				'RestockWeight', 25,
				'CategoryPair', "Ordnance",
				'PenetrationClass', 1,
				'BurnGround', false,
				'Caliber', "MortarShell",
				'BaseDamage', 0,
				'Noise', 0,
				'aoeType', "smoke",
			}),
			PlaceObj('ModItemInventoryItemCompositeDef', {
				'Group', "Ammo - Ordnance",
				'Id', "_40mmFlashbangGrenade",
				'object_class', "Ordnance",
				'Icon', "UI/Icons/Items/40mm_flashbang_grenade",
				'DisplayName', T(886826508035, --[[ModItemInventoryItemCompositeDef _40mmFlashbangGrenade DisplayName]] "40 mm Flashbang"),
				'DisplayNamePlural', T(414325610296, --[[ModItemInventoryItemCompositeDef _40mmFlashbangGrenade DisplayNamePlural]] "40 mm Flashbangs"),
				'Description', T(611944552839, --[[ModItemInventoryItemCompositeDef _40mmFlashbangGrenade Description]] "40 mm ordnance ammo for Grenade Launchers."),
				'AdditionalHint', T(237735748307, --[[ModItemInventoryItemCompositeDef _40mmFlashbangGrenade AdditionalHint]] "<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Causes <color EmStyle>Suppressed</color>\n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Causes <color EmStyle>Dazed</color>\n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Cancel readied attacks\n"),
				'Cost', 850,
				'CanAppearInShop', true,
				'Tier', 2,
				'MaxStock', 5,
				'RestockWeight', 25,
				'CategoryPair', "Ordnance",
				'CenterUnitDamageMod', 130,
				'CenterObjDamageMod', 10,
				'AreaObjDamageMod', 10,
				'PenetrationClass', 1,
				'BurnGround', false,
				'Caliber', "40mmGrenade",
				'BaseDamage', 5,
				'Noise', 40,
				'Entity', "Weapon_MilkorMGL_Shell",
			}),
			}),
		PlaceObj('ModItemFolder', {
			'name', "IEDs",
		}, {
			PlaceObj('ModItemInventoryItemCompositeDef', {
				'Group', "Grenade - Explosive",
				'Id', "TNTBolt_IED",
				'object_class', "Grenade",
				'Repairable', false,
				'Reliability', 100,
				'Icon', "Mod/RATONADE/Images/nailbomb2 3.png",
				'ItemType', "Grenade",
				'DisplayName', T(564860260183, --[[ModItemInventoryItemCompositeDef TNTBolt_IED DisplayName]] "Fragmentary TNT Stick"),
				'DisplayNamePlural', T(735927037683, --[[ModItemInventoryItemCompositeDef TNTBolt_IED DisplayNamePlural]] "Fragmentary TNT Sticks"),
				'AdditionalHint', T(639163114527, --[[ModItemInventoryItemCompositeDef TNTBolt_IED AdditionalHint]] "<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Explodes immediately"),
				'UnitStat', "Explosives",
				'Cost', 400,
				'CanAppearInShop', true,
				'Tier', 2,
				'CategoryPair', "Grenade",
				'MinMishapChance', -2,
				'MaxMishapChance', 18,
				'MaxMishapRange', 6,
				'CenterUnitDamageMod', 130,
				'CenterObjDamageMod', 500,
				'AreaObjDamageMod', 500,
				'PenetrationClass', 4,
				'DeathType', "BlowUp",
				'Entity', "World_Flarestick_01",
				'ActionIcon', "UI/Icons/Hud/throw_grenade",
			}),
			PlaceObj('ModItemInventoryItemCompositeDef', {
				'Group', "Grenade - Explosive",
				'Id', "NailBomb_IED",
				'object_class', "Grenade",
				'Repairable', false,
				'Reliability', 100,
				'Icon', "Mod/RATONADE/Images/nailbomb2 4.png",
				'ItemType', "Grenade",
				'DisplayName', T(439953250262, --[[ModItemInventoryItemCompositeDef NailBomb_IED DisplayName]] "Nail Bomb"),
				'DisplayNamePlural', T(880534339154, --[[ModItemInventoryItemCompositeDef NailBomb_IED DisplayNamePlural]] "Nail Bombs"),
				'AdditionalHint', T(808458367295, --[[ModItemInventoryItemCompositeDef NailBomb_IED AdditionalHint]] "<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Explodes immediately"),
				'UnitStat', "Explosives",
				'Cost', 400,
				'CanAppearInShop', true,
				'Tier', 2,
				'CategoryPair', "Grenade",
				'MinMishapChance', -2,
				'MaxMishapChance', 18,
				'MaxMishapRange', 6,
				'CenterUnitDamageMod', 130,
				'CenterObjDamageMod', 500,
				'AreaObjDamageMod', 500,
				'PenetrationClass', 4,
				'DeathType', "BlowUp",
				'Entity', "World_Flarestick_01",
				'ActionIcon', "UI/Icons/Hud/throw_grenade",
			}),
			PlaceObj('ModItemInventoryItemCompositeDef', {
				'Group', "Grenade - Throwable",
				'Id', "SmokeGrenade_IED",
				'object_class', "Grenade",
				'Repairable', false,
				'Reliability', 100,
				'Icon', "Mod/RATONADE/Images/smoke_ied.png",
				'ItemType', "Throwables",
				'DisplayName', T(603817580280, --[[ModItemInventoryItemCompositeDef SmokeGrenade_IED DisplayName]] "Smoke Grenade"),
				'DisplayNamePlural', T(521720469032, --[[ModItemInventoryItemCompositeDef SmokeGrenade_IED DisplayNamePlural]] "Smoke Grenades"),
				'AdditionalHint', T(953201278809, --[[ModItemInventoryItemCompositeDef SmokeGrenade_IED AdditionalHint]] "<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Ranged attacks passing through gas become <color EmStyle>grazing</color> hits\n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> No damage\n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Almost silent"),
				'UnitStat', "Explosives",
				'Cost', 600,
				'CanAppearInShop', true,
				'Tier', 2,
				'RestockWeight', 25,
				'CategoryPair', "Grenade",
				'MinMishapChance', -2,
				'MaxMishapChance', 18,
				'MinMishapRange', 0,
				'CenterUnitDamageMod', 0,
				'CenterObjDamageMod', 0,
				'AreaUnitDamageMod', 0,
				'AreaObjDamageMod', 0,
				'PenetrationClass', 1,
				'BaseDamage', 0,
				'Scatter', 4,
				'AttackAP', 4000,
				'InaccurateMaxOffset', 3000,
				'Noise', 0,
				'aoeType', "smoke",
				'Entity', "Weapon_SmokeGrenade_Test",
				'ActionIcon', "UI/Icons/Hud/smoke_grenade",
				'r_timer', 3500,
				'r_mass', 610,
				'r_shape', "Cylindrical",
			}),
			PlaceObj('ModItemInventoryItemCompositeDef', {
				'Group', "Grenade - Throwable",
				'Id', "Molotov",
				'object_class', "Grenade",
				'Repairable', false,
				'Reliability', 100,
				'Icon', "UI/Icons/Weapons/Molotov",
				'ItemType', "GrenadeFire",
				'DisplayName', T(270380819426, --[[ModItemInventoryItemCompositeDef Molotov DisplayName]] "Molotov Cocktail"),
				'DisplayNamePlural', T(717638534602, --[[ModItemInventoryItemCompositeDef Molotov DisplayNamePlural]] "Molotov Cocktails"),
				'AdditionalHint', T(496178231258, --[[ModItemInventoryItemCompositeDef Molotov AdditionalHint]] "<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Sets an area on fire and inflicts <color EmStyle>Burning</color>\n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> High mishap chance"),
				'UnitStat', "Explosives",
				'Cost', 300,
				'CanAppearInShop', true,
				'RestockWeight', 50,
				'CategoryPair', "Grenade",
				'MinMishapChance', 2,
				'MaxMishapChance', 30,
				'MinMishapRange', 0,
				'CenterUnitDamageMod', 0,
				'CenterObjDamageMod', 0,
				'AreaUnitDamageMod', 0,
				'AreaObjDamageMod', 0,
				'PenetrationClass', 1,
				'BaseDamage', 0,
				'Scatter', 4,
				'AttackAP', 4000,
				'BaseRange', 4,
				'ThrowMaxRange', 12,
				'CanBounce', false,
				'InaccurateMaxOffset', 4000,
				'Noise', 0,
				'aoeType', "fire",
				'Entity', "Weapon_MolotovCocktail",
				'ActionIcon', "UI/Icons/Hud/molotov",
				'r_timer', 7000,
				'r_mass', 980,
				'r_shape', "Bottle",
				'is_ied', true,
			}),
			PlaceObj('ModItemInventoryItemCompositeDef', {
				'Group', "Grenade - Explosive",
				'Id', "Pipe_IED",
				'object_class', "ThrowableTrapItem",
				'Repairable', false,
				'Reliability', 100,
				'Icon', "Mod/RATONADE/Images/pipebomb.png",
				'ItemType', "Grenade",
				'DisplayName', T(343108932526, --[[ModItemInventoryItemCompositeDef Pipe_IED DisplayName]] "Pipe Bomb"),
				'DisplayNamePlural', T(885497071669, --[[ModItemInventoryItemCompositeDef Pipe_IED DisplayNamePlural]] "Pipe Bombs"),
				'AdditionalHint', T(392517442086, --[[ModItemInventoryItemCompositeDef Pipe_IED AdditionalHint]] "<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Explodes after 1 turn (or 5 seconds out of combat)\n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> High mishap chance\n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Inflicts Bleeding"),
				'UnitStat', "Explosives",
				'Cost', 100,
				'CanAppearInShop', true,
				'RestockWeight', 50,
				'CategoryPair', "Grenade",
				'MinMishapChance', 2,
				'MaxMishapChance', 30,
				'MaxMishapRange', 6,
				'CenterUnitDamageMod', 130,
				'CenterAppliedEffects', {
					"Bleeding",
				},
				'AttackAP', 3000,
				'BaseRange', 3,
				'ThrowMaxRange', 12,
				'Entity', "Explosive_TNT",
				'ActionIcon', "UI/Icons/Hud/pipe_bomb",
				'r_timer', 5000,
				'r_mass', 980,
				'r_shape', "Long",
				'is_ied', true,
				'r_shrap_num', 180,
				'TimedExplosiveTurns', 0,
				'ExplosiveType', "BlackPowder",
			}),
			PlaceObj('ModItemInventoryItemCompositeDef', {
				'Group', "Grenade - Explosive",
				'Id', "PipeBomb",
				'object_class', "ThrowableTrapItem",
				'Repairable', false,
				'Reliability', 100,
				'Icon', "UI/Icons/Weapons/PipeBomb",
				'SubIcon', "UI/Icons/Weapons/PipeBomb",
				'ItemType', "Grenade",
				'DisplayName', T(757629881557, --[[ModItemInventoryItemCompositeDef PipeBomb DisplayName]] "Delayed Pipe Bomb"),
				'DisplayNamePlural', T(532583650085, --[[ModItemInventoryItemCompositeDef PipeBomb DisplayNamePlural]] "Delayed Pipe Bombs"),
				'AdditionalHint', T(570167775923, --[[ModItemInventoryItemCompositeDef PipeBomb AdditionalHint]] "<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Explodes after 1 turn (or 5 seconds out of combat)\n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> High mishap chance\n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Inflicts <color EmStyle>Bleeding</color>."),
				'UnitStat', "Explosives",
				'Cost', 300,
				'CanAppearInShop', true,
				'RestockWeight', 50,
				'CategoryPair', "Grenade",
				'MinMishapChance', 2,
				'MaxMishapChance', 30,
				'MinMishapRange', 0,
				'CenterUnitDamageMod', 130,
				'CenterAppliedEffects', {
					"Bleeding",
				},
				'Scatter', 4,
				'AttackAP', 3000,
				'BaseRange', 3,
				'ThrowMaxRange', 12,
				'InaccurateMaxOffset', 3000,
				'Entity', "Explosive_TNT",
				'ActionIcon', "UI/Icons/Hud/pipe_bomb",
				'r_mass', 980,
				'r_shape', "Long",
				'is_ied', true,
				'r_shrap_num', 175,
				'TriggerType', "Timed",
				'ExplosiveType', "BlackPowder",
			}),
			PlaceObj('ModItemInventoryItemCompositeDef', {
				'Group', "Ammo - Ordnance",
				'Id', "Warhead_Frag_IED",
				'object_class', "Ordnance",
				'Icon', "Mod/RATONADE/Images/warhead_icon 2.png",
				'DisplayName', T(439242608885, --[[ModItemInventoryItemCompositeDef Warhead_Frag_IED DisplayName]] "HE Rocket"),
				'DisplayNamePlural', T(250143006457, --[[ModItemInventoryItemCompositeDef Warhead_Frag_IED DisplayNamePlural]] "HE Rockets"),
				'Description', T(261557488921, --[[ModItemInventoryItemCompositeDef Warhead_Frag_IED Description]] "Ordnance ammo for Rocket Launchers."),
				'AdditionalHint', T(444721835227, --[[ModItemInventoryItemCompositeDef Warhead_Frag_IED AdditionalHint]] "<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Inflicts Suppressed in the epicenter"),
				'Cost', 400,
				'CanAppearInShop', true,
				'Tier', 3,
				'MaxStock', 5,
				'RestockWeight', 50,
				'CategoryPair', "Ordnance",
				'CenterUnitDamageMod', 130,
				'CenterObjDamageMod', 500,
				'CenterAppliedEffects', {
					"Suppressed",
				},
				'AreaOfEffect', 2,
				'AreaObjDamageMod', 500,
				'DeathType', "BlowUp",
				'Caliber', "Warhead",
				'BaseDamage', 50,
				'Noise', 30,
			}),
			PlaceObj('ModItemInventoryItemCompositeDef', {
				'Group', "Grenade - Explosive",
				'Id', "TearGasGrenade_IED",
				'object_class', "Grenade",
				'Repairable', false,
				'Reliability', 100,
				'Icon', "Mod/RATONADE/Images/TEAR2_ied.png",
				'ItemType', "GrenadeGas",
				'DisplayName', T(992290877366, --[[ModItemInventoryItemCompositeDef TearGasGrenade_IED DisplayName]] "Tear Gas Grenade"),
				'DisplayNamePlural', T(520192725614, --[[ModItemInventoryItemCompositeDef TearGasGrenade_IED DisplayNamePlural]] "Tear Gas Grenades"),
				'AdditionalHint', T(468937308243, --[[ModItemInventoryItemCompositeDef TearGasGrenade_IED AdditionalHint]] "<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Inflicts <color EmStyle>Blinded</color>\n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Ranged attacks passing through gas become <color EmStyle>grazing</color> hits\n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> No damage\n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> High mishap chance\n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Almost silent"),
				'UnitStat', "Explosives",
				'Cost', 800,
				'CanAppearInShop', true,
				'Tier', 2,
				'RestockWeight', 25,
				'CategoryPair', "Grenade",
				'MinMishapChance', 2,
				'MaxMishapChance', 30,
				'MinMishapRange', 0,
				'CenterUnitDamageMod', 0,
				'CenterObjDamageMod', 0,
				'AreaUnitDamageMod', 0,
				'AreaObjDamageMod', 0,
				'PenetrationClass', 1,
				'BaseDamage', 0,
				'Scatter', 4,
				'AttackAP', 4000,
				'InaccurateMaxOffset', 4000,
				'Noise', 0,
				'aoeType', "teargas",
				'Entity', "Weapon_MolotovCocktail",
				'ActionIcon', "UI/Icons/Hud/tear_gas_grenade",
				'r_timer', 4000,
				'r_mass', 610,
				'r_shape', "Cylindrical",
			}),
			PlaceObj('ModItemInventoryItemCompositeDef', {
				'Group', "Grenade - Throwable",
				'Id', "ConcussiveGrenade_IED",
				'object_class', "Grenade",
				'Repairable', false,
				'Reliability', 100,
				'Icon', "Mod/RATONADE/Images/flash_ied 3.png",
				'ItemType', "Grenade",
				'DisplayName', T(919480215237, --[[ModItemInventoryItemCompositeDef ConcussiveGrenade_IED DisplayName]] "Flashbang"),
				'DisplayNamePlural', T(462067699032, --[[ModItemInventoryItemCompositeDef ConcussiveGrenade_IED DisplayNamePlural]] "Flashbangs"),
				'AdditionalHint', T(261788256938, --[[ModItemInventoryItemCompositeDef ConcussiveGrenade_IED AdditionalHint]] "<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Causes <color EmStyle>Suppressed</color>\n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Causes <color EmStyle>Dazed</color>\n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Cancel readied attacks\n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Very loud. That's the point of this grenade"),
				'UnitStat', "Explosives",
				'Cost', 800,
				'CanAppearInShop', true,
				'Tier', 2,
				'RestockWeight', 25,
				'CategoryPair', "Grenade",
				'MinMishapChance', -2,
				'MaxMishapChance', 18,
				'MinMishapRange', 0,
				'CenterUnitDamageMod', 0,
				'CenterObjDamageMod', 0,
				'CenterAppliedEffects', {
					"Suppressed",
					"dazed_flashbang",
					"cancel_shot_flashbang",
				},
				'AreaUnitDamageMod', 0,
				'AreaObjDamageMod', 0,
				'AreaAppliedEffects', {
					"Suppressed",
					"dazed_flashbang",
					"cancel_shot_flashbang",
				},
				'PenetrationClass', 1,
				'BurnGround', false,
				'BaseDamage', 0,
				'Scatter', 4,
				'AttackAP', 4000,
				'InaccurateMaxOffset', 4000,
				'Noise', 40,
				'Entity', "Weapon_StunGrenadeM84",
				'ActionIcon', "UI/Icons/Hud/concussive_grenade",
				'r_timer', 3000,
				'r_mass', 370,
				'r_shape', "Cylindrical",
			}),
			}),
		PlaceObj('ModItemFolder', {
			'name', "New Explosives",
		}, {
			PlaceObj('ModItemInventoryItemCompositeDef', {
				'Group', "Grenade - Throwable",
				'Id', "IncendiaryGrenade",
				'object_class', "Grenade",
				'Repairable', false,
				'Reliability', 100,
				'Icon', "Mod/RATONADE/Images/incendiary2.png",
				'ItemType', "GrenadeFire",
				'DisplayName', T(690193619979, --[[ModItemInventoryItemCompositeDef IncendiaryGrenade DisplayName]] "Incendiary Grenade"),
				'DisplayNamePlural', T(169272979158, --[[ModItemInventoryItemCompositeDef IncendiaryGrenade DisplayNamePlural]] "Incendiary Grenades"),
				'AdditionalHint', T(622520137835, --[[ModItemInventoryItemCompositeDef IncendiaryGrenade AdditionalHint]] "<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Sets an area on fire and inflicts <color EmStyle>Burning</color>\n"),
				'UnitStat', "Explosives",
				'Cost', 300,
				'CanAppearInShop', true,
				'RestockWeight', 50,
				'CategoryPair', "Grenade",
				'MinMishapChance', 2,
				'MaxMishapChance', 30,
				'MinMishapRange', 0,
				'CenterUnitDamageMod', 0,
				'CenterObjDamageMod', 0,
				'CenterAppliedEffects', {
					"Burning",
				},
				'AreaOfEffect', 4,
				'AreaUnitDamageMod', 0,
				'AreaObjDamageMod', 0,
				'AreaAppliedEffects', {
					"Burning",
				},
				'PenetrationClass', 1,
				'BaseDamage', 0,
				'Scatter', 4,
				'AttackAP', 4000,
				'InaccurateMaxOffset', 4000,
				'Noise', 0,
				'aoeType', "fire",
				'Entity', "Weapon_MolotovCocktail",
				'ActionIcon', "UI/Icons/Hud/molotov",
				'r_mass', 400,
				'r_shape', "Cylindrical",
			}),
			PlaceObj('ModItemInventoryItemCompositeDef', {
				'Group', "Grenade - Explosive",
				'Id', "HE_Grenade_1",
				'object_class', "Grenade",
				'Repairable', false,
				'Reliability', 100,
				'Icon', "Mod/RATONADE/Images/he2 4.png",
				'ItemType', "Grenade",
				'DisplayName', T(863833209471, --[[ModItemInventoryItemCompositeDef HE_Grenade_1 DisplayName]] "High Explosive Grenade"),
				'DisplayNamePlural', T(493053531072, --[[ModItemInventoryItemCompositeDef HE_Grenade_1 DisplayNamePlural]] "High Explosive Grenades"),
				'Description', T(868146148463, --[[ModItemInventoryItemCompositeDef HE_Grenade_1 Description]] "<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120>Inflicts <color EmStyle>Bleeding</color>"),
				'AdditionalHint', T(928260625708, --[[ModItemInventoryItemCompositeDef HE_Grenade_1 AdditionalHint]] "<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Knocks down units \n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Smaller area\n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Good at destroying objects\n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Penetrates any armor\n"),
				'UnitStat', "Explosives",
				'Cost', 400,
				'CanAppearInShop', true,
				'Tier', 2,
				'CategoryPair', "Grenade",
				'MinMishapChance', -2,
				'MaxMishapChance', 18,
				'MinMishapRange', 0,
				'CenterUnitDamageMod', 130,
				'CenterObjDamageMod', 500,
				'CenterAppliedEffects', {
					"KnockDown",
				},
				'AreaObjDamageMod', 500,
				'AreaAppliedEffects', {
					"KnockDown",
				},
				'BurnGround', false,
				'DeathType', "BlowUp",
				'BaseDamage', 35,
				'Scatter', 4,
				'BaseRange', 7,
				'ThrowMaxRange', 17,
				'InaccurateMaxOffset', 3000,
				'Noise', 30,
				'Entity', "MilitaryCamp_Grenade_02",
				'ActionIcon', "UI/Icons/Hud/throw_grenade",
				'r_mass', 600,
				'r_shape', "Cylindrical",
			}),
			}),
		PlaceObj('ModItemInventoryItemCompositeDef', {
			'Group', "Grenade - Throwable",
			'Id', "ConcussiveGrenade",
			'object_class', "Grenade",
			'Repairable', false,
			'Reliability', 100,
			'Icon', "UI/Icons/Weapons/ConcussiveGrenade",
			'ItemType', "Grenade",
			'DisplayName', T(121480336412, --[[ModItemInventoryItemCompositeDef ConcussiveGrenade DisplayName]] "Flashbang"),
			'DisplayNamePlural', T(350652266241, --[[ModItemInventoryItemCompositeDef ConcussiveGrenade DisplayNamePlural]] "Flashbangs"),
			'AdditionalHint', T(340204864818, --[[ModItemInventoryItemCompositeDef ConcussiveGrenade AdditionalHint]] "<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Causes <color EmStyle>Suppressed</color>\n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Causes <color EmStyle>Dazed</color>\n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Cancel readied attacks\n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Very loud. That's the point of this grenade"),
			'UnitStat', "Explosives",
			'Cost', 800,
			'CanAppearInShop', true,
			'Tier', 2,
			'RestockWeight', 25,
			'CategoryPair', "Grenade",
			'MinMishapChance', -2,
			'MaxMishapChance', 18,
			'MinMishapRange', 0,
			'CenterUnitDamageMod', 0,
			'CenterObjDamageMod', 0,
			'CenterAppliedEffects', {
				"cancel_shot_flashbang",
				"Suppressed",
				"dazed_flashbang",
				"KnockDown",
			},
			'AreaUnitDamageMod', 0,
			'AreaObjDamageMod', 0,
			'AreaAppliedEffects', {
				"cancel_shot_flashbang",
				"Suppressed",
				"dazed_flashbang",
			},
			'PenetrationClass', 1,
			'BurnGround', false,
			'BaseDamage', 0,
			'Scatter', 4,
			'AttackAP', 4000,
			'BaseRange', 10,
			'ThrowMaxRange', 22,
			'InaccurateMaxOffset', 4000,
			'Noise', 40,
			'Entity', "Weapon_StunGrenadeM84",
			'ActionIcon', "UI/Icons/Hud/concussive_grenade",
			'r_timer', 3000,
			'r_mass', 370,
			'r_shape', "Cylindrical",
		}),
		PlaceObj('ModItemInventoryItemCompositeDef', {
			'Group', "Grenade - Explosive",
			'Id', "TearGasGrenade",
			'object_class', "Grenade",
			'Repairable', false,
			'Reliability', 100,
			'Icon', "UI/Icons/Weapons/TearGasGrenade",
			'ItemType', "GrenadeGas",
			'DisplayName', T(730452939433, --[[ModItemInventoryItemCompositeDef TearGasGrenade DisplayName]] "Tear Gas Grenade"),
			'DisplayNamePlural', T(479472585395, --[[ModItemInventoryItemCompositeDef TearGasGrenade DisplayNamePlural]] "Tear Gas Grenades"),
			'AdditionalHint', T(626078520609, --[[ModItemInventoryItemCompositeDef TearGasGrenade AdditionalHint]] "<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Inflicts <color EmStyle>Blinded</color>\n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Ranged attacks passing through gas become <color EmStyle>grazing</color> hits\n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> No damage\n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> High mishap chance\n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Almost silent"),
			'UnitStat', "Explosives",
			'Cost', 800,
			'CanAppearInShop', true,
			'Tier', 2,
			'RestockWeight', 25,
			'CategoryPair', "Grenade",
			'MinMishapChance', 2,
			'MaxMishapChance', 30,
			'MinMishapRange', 0,
			'CenterUnitDamageMod', 0,
			'CenterObjDamageMod', 0,
			'AreaUnitDamageMod', 0,
			'AreaObjDamageMod', 0,
			'PenetrationClass', 1,
			'BaseDamage', 0,
			'Scatter', 4,
			'AttackAP', 4000,
			'InaccurateMaxOffset', 4000,
			'Noise', 0,
			'aoeType', "teargas",
			'Entity', "Weapon_MolotovCocktail",
			'ActionIcon', "UI/Icons/Hud/tear_gas_grenade",
			'r_timer', 4000,
			'r_mass', 610,
			'r_shape', "Cylindrical",
		}),
		PlaceObj('ModItemInventoryItemCompositeDef', {
			'Group', "Grenade - Explosive",
			'Id', "FragGrenade",
			'object_class', "Grenade",
			'Repairable', false,
			'Reliability', 100,
			'Icon', "UI/Icons/Weapons/Frag Grenade",
			'ItemType', "Grenade",
			'DisplayName', T(884807926062, --[[ModItemInventoryItemCompositeDef FragGrenade DisplayName]] "Stick Grenade"),
			'DisplayNamePlural', T(765773516877, --[[ModItemInventoryItemCompositeDef FragGrenade DisplayNamePlural]] "Stick Grenades"),
			'Description', "",
			'AdditionalHint', "",
			'UnitStat', "Explosives",
			'Cost', 400,
			'CanAppearInShop', true,
			'CategoryPair', "Grenade",
			'MinMishapChance', -2,
			'MaxMishapChance', 18,
			'MinMishapRange', 0,
			'MaxMishapRange', 3,
			'CenterUnitDamageMod', 130,
			'CenterObjDamageMod', 200,
			'AreaObjDamageMod', 250,
			'PenetrationClass', 4,
			'DeathType', "BlowUp",
			'BaseDamage', 22,
			'Scatter', 4,
			'BaseRange', 7,
			'ThrowMaxRange', 17,
			'InaccurateMaxOffset', 3000,
			'Entity', "MilitaryCamp_Grenade_01",
			'ActionIcon', "UI/Icons/Hud/frag_grenade",
			'r_timer', 6500,
			'r_mass', 595,
			'r_shape', "Stick_like",
			'r_shrap_num', 300,
		}),
		PlaceObj('ModItemInventoryItemCompositeDef', {
			'Group', "Quest - Items",
			'Id', "ShapedCharge",
			'object_class', "Grenade",
			'Repairable', false,
			'Reliability', 100,
			'Icon', "UI/Icons/Weapons/ShapedCharge",
			'ItemType', "Grenade",
			'DisplayName', T(880214712809, --[[ModItemInventoryItemCompositeDef ShapedCharge DisplayName]] "Shaped Charge"),
			'DisplayNamePlural', T(611415893484, --[[ModItemInventoryItemCompositeDef ShapedCharge DisplayNamePlural]] "Shaped Charges"),
			'AdditionalHint', T(832446983932, --[[ModItemInventoryItemCompositeDef ShapedCharge AdditionalHint]] "<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Cone-shaped explosion\n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Very low accuracy when used by anyone except Barry "),
			'UnitStat', "Explosives",
			'Cost', 1500,
			'MinMishapChance', -2,
			'MaxMishapChance', 18,
			'MinMishapRange', 0,
			'AreaOfEffect', 8,
			'PenetrationClass', 3,
			'coneShaped', true,
			'coneAngle', 40,
			'BurnGround', false,
			'DeathType', "BlowUp",
			'BaseDamage', 38,
			'Scatter', 4,
			'CanBounce', false,
			'InaccurateMaxOffset', 4000,
			'Entity', "MilitaryCamp_Grenade_01",
			'ActionIcon', "UI/Icons/Hud/shaped_charge",
			'r_mass', 1070,
			'r_shape', "Stick_like",
			'r_shrap_num', 300,
		}),
		PlaceObj('ModItemInventoryItemCompositeDef', {
			'Group', "Grenade - Explosive",
			'Id', "HE_Grenade",
			'object_class', "Grenade",
			'Repairable', false,
			'Reliability', 100,
			'Icon', "UI/Icons/Weapons/HEGrenade",
			'SubIcon', "Mod/TU6SADg/Images/bleed3.png",
			'ItemType', "Grenade",
			'DisplayName', T(547996004204, --[[ModItemInventoryItemCompositeDef HE_Grenade DisplayName]] "Fragmentation Grenade"),
			'DisplayNamePlural', T(440377233591, --[[ModItemInventoryItemCompositeDef HE_Grenade DisplayNamePlural]] "Fragmentation Grenade"),
			'Description', T(336775963908, --[[ModItemInventoryItemCompositeDef HE_Grenade Description]] "<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120>Inflicts <color EmStyle>Bleeding</color>"),
			'AdditionalHint', "",
			'UnitStat', "Explosives",
			'Cost', 600,
			'CanAppearInShop', true,
			'Tier', 2,
			'CategoryPair', "Grenade",
			'MinMishapChance', -2,
			'MaxMishapChance', 18,
			'MinMishapRange', 0,
			'CenterUnitDamageMod', 130,
			'CenterObjDamageMod', 200,
			'AreaObjDamageMod', 250,
			'PenetrationClass', 4,
			'DeathType', "BlowUp",
			'BaseDamage', 35,
			'Scatter', 4,
			'BaseRange', 8,
			'ThrowMaxRange', 19,
			'InaccurateMaxOffset', 3000,
			'Entity', "MilitaryCamp_Grenade_02",
			'ActionIcon', "UI/Icons/Hud/throw_grenade",
			'r_timer', 4500,
			'r_mass', 600,
			'r_shape', "Spherical",
			'r_shrap_num', 1000,
		}),
		PlaceObj('ModItemInventoryItemCompositeDef', {
			'Group', "Grenade - Throwable",
			'Id', "FlareStick",
			'object_class', "Flare",
			'Repairable', false,
			'Reliability', 100,
			'Icon', "UI/Icons/Weapons/FlareStick",
			'ItemType', "Throwables",
			'DisplayName', T(509204256542, --[[ModItemInventoryItemCompositeDef FlareStick DisplayName]] "Flare Stick"),
			'DisplayNamePlural', T(784449735534, --[[ModItemInventoryItemCompositeDef FlareStick DisplayNamePlural]] "Flare Sticks"),
			'AdditionalHint', T(390050967382, --[[ModItemInventoryItemCompositeDef FlareStick AdditionalHint]] "<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Illuminates a large area\n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> High mishap chance\n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Silent"),
			'UnitStat', "Explosives",
			'Cost', 200,
			'CanAppearInShop', true,
			'Tier', 2,
			'RestockWeight', 25,
			'CategoryPair', "Grenade",
			'MinMishapChance', 10,
			'MaxMishapChance', 50,
			'MaxMishapRange', 6,
			'CenterUnitDamageMod', 0,
			'CenterObjDamageMod', 0,
			'AreaOfEffect', 4,
			'AreaUnitDamageMod', 0,
			'AreaObjDamageMod', 0,
			'PenetrationClass', 1,
			'BaseDamage', 0,
			'Scatter', 4,
			'AttackAP', 4000,
			'Noise', 0,
			'Entity', "Weapon_MolotovCocktail",
			'ActionIcon', "UI/Icons/Hud/flare",
			'is_explosive', false,
			'r_mass', 580,
			'r_shape', "Long",
		}),
		PlaceObj('ModItemInventoryItemCompositeDef', {
			'Group', "Grenade - Throwable",
			'Id', "GlowStick",
			'object_class', "Flare",
			'Repairable', false,
			'Reliability', 100,
			'Icon', "UI/Icons/Weapons/GlowStick",
			'ItemType', "Throwables",
			'DisplayName', T(613585253014, --[[ModItemInventoryItemCompositeDef GlowStick DisplayName]] "Glow Stick"),
			'DisplayNamePlural', T(894985193700, --[[ModItemInventoryItemCompositeDef GlowStick DisplayNamePlural]] "Glow Sticks"),
			'AdditionalHint', T(772000348805, --[[ModItemInventoryItemCompositeDef GlowStick AdditionalHint]] "<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Illuminates a small area"),
			'UnitStat', "Explosives",
			'Cost', 100,
			'CanAppearInShop', true,
			'Tier', 2,
			'RestockWeight', 50,
			'CategoryPair', "Grenade",
			'MinMishapChance', -2,
			'MaxMishapChance', 18,
			'MaxMishapRange', 6,
			'CenterUnitDamageMod', 0,
			'CenterObjDamageMod', 0,
			'AreaOfEffect', 2,
			'AreaUnitDamageMod', 0,
			'AreaObjDamageMod', 0,
			'PenetrationClass', 1,
			'BaseDamage', 0,
			'Scatter', 4,
			'AttackAP', 2000,
			'BaseRange', 10,
			'ThrowMaxRange', 20,
			'CanBounce', false,
			'Noise', 0,
			'Entity', "Weapon_MolotovCocktail",
			'ActionIcon', "UI/Icons/Hud/throw_glowstick",
			'is_explosive', false,
			'r_mass', 270,
			'r_shape', "Long",
			'ExpirationTurns', 10,
		}),
		PlaceObj('ModItemInventoryItemCompositeDef', {
			'Group', "Grenade - Throwable",
			'Id', "SmokeGrenade",
			'object_class', "Grenade",
			'Repairable', false,
			'Reliability', 100,
			'Icon', "UI/Icons/Weapons/SmokeGrenade",
			'ItemType', "Throwables",
			'DisplayName', T(110395037196, --[[ModItemInventoryItemCompositeDef SmokeGrenade DisplayName]] "Smoke Grenade"),
			'DisplayNamePlural', T(568709088875, --[[ModItemInventoryItemCompositeDef SmokeGrenade DisplayNamePlural]] "Smoke Grenades"),
			'AdditionalHint', T(368187604805, --[[ModItemInventoryItemCompositeDef SmokeGrenade AdditionalHint]] "<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Ranged attacks passing through gas become <color EmStyle>grazing</color> hits\n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> No damage\n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Almost silent"),
			'UnitStat', "Explosives",
			'Cost', 600,
			'CanAppearInShop', true,
			'Tier', 2,
			'RestockWeight', 25,
			'CategoryPair', "Grenade",
			'MinMishapChance', -2,
			'MaxMishapChance', 18,
			'MinMishapRange', 0,
			'CenterUnitDamageMod', 0,
			'CenterObjDamageMod', 0,
			'AreaUnitDamageMod', 0,
			'AreaObjDamageMod', 0,
			'PenetrationClass', 1,
			'BaseDamage', 0,
			'Scatter', 4,
			'AttackAP', 4000,
			'InaccurateMaxOffset', 3000,
			'Noise', 0,
			'aoeType', "smoke",
			'Entity', "Weapon_SmokeGrenade_Test",
			'ActionIcon', "UI/Icons/Hud/smoke_grenade",
			'r_timer', 3500,
			'r_mass', 610,
			'r_shape', "Cylindrical",
		}),
		PlaceObj('ModItemInventoryItemCompositeDef', {
			'Group', "Grenade - Throwable",
			'Id', "ToxicGasGrenade",
			'object_class', "Grenade",
			'Repairable', false,
			'Reliability', 100,
			'Icon', "UI/Icons/Weapons/ToxicGrenade",
			'ItemType', "GrenadeGas",
			'DisplayName', T(909015576514, --[[ModItemInventoryItemCompositeDef ToxicGasGrenade DisplayName]] "Mustard Gas Grenade"),
			'DisplayNamePlural', T(564413611846, --[[ModItemInventoryItemCompositeDef ToxicGasGrenade DisplayNamePlural]] "Mustard Gas Grenades"),
			'AdditionalHint', T(448195976024, --[[ModItemInventoryItemCompositeDef ToxicGasGrenade AdditionalHint]] "<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Inflicts <color EmStyle>Choking</color>\n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Ranged attacks passing through gas become grazing hits\n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> High mishap chance\n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Almost silent"),
			'UnitStat', "Explosives",
			'Cost', 1500,
			'MinMishapChance', 2,
			'MaxMishapChance', 30,
			'MinMishapRange', 0,
			'CenterUnitDamageMod', 0,
			'CenterObjDamageMod', 0,
			'AreaUnitDamageMod', 0,
			'AreaObjDamageMod', 0,
			'PenetrationClass', 3,
			'BaseDamage', 0,
			'Scatter', 4,
			'AttackAP', 4000,
			'InaccurateMaxOffset', 3000,
			'Noise', 0,
			'aoeType', "toxicgas",
			'Entity', "Weapon_MolotovCocktail",
			'ActionIcon', "UI/Icons/Hud/toxic_grenade",
			'r_timer', 4000,
			'r_mass', 610,
			'r_shape', "Cylindrical",
		}),
		}),
}