return PlaceObj('ModDef', {
	'title', "Rato's Explosive Overhaul 2.0",
	'description', "implement bounce speed diminish depending on angle\n\n\ndetermine mishap chances",
	'id', "RATONADE",
	'author', "rato",
	'version', 2188,
	'lua_revision', 233360,
	'saved_with_revision', 350233,
	'entities', {
		"nail_can",
		"tear_can",
		"flash_can",
		"smoke_can",
	},
	'code', {
		"CharacterEffect/cancel_shot_flashbang.lua",
		"CharacterEffect/dazed_flashbang.lua",
		"Code/SOURCE_CalcBounceParabola_LUA.lua",
		"Code/SOURCE_AnimGrenadeTraj.lua",
		"Code/SOURCE_GrenadeGetAttackResults.lua",
		"Code/SOURCE_SmokePropagate.lua",
		"Code/SOURCE_HeavyWeaponsGetAttackResults.lua",
		"Code/SOURCE_ThrowableTrapOnLand.lua",
		"Code/SOURCE_GrenadeOnLand.lua",
		"Code/SOURCE_GrenadeMishapChance.lua",
		"Code/SOURCE_UnitThrowGrenade.lua",
		"Code/SOURCE_GrenadeGetTrajectory.lua",
		"Code/FUNCTIONS_BounceGrenade.lua",
		"Code/FUNCTIONS_DeviateGrenade.lua",
		"Code/FUNCTIONS_DeviateHeavyWeapons.lua",
		"Code/FUNCTIONS_GrenadeCalcTrajectory.lua",
		"Code/FUNCTION_BounceObjMaterialSpeed.lua",
		"Code/FUNCTIONS_Debug.lua",
		"Code/FUNCTIONS_Shrapnel.lua",
		"Code/FUNCTIONS_Util.lua",
		"Code/FUNCTION_ItemChanges.lua",
		"Code/FUNCTIONS_AIAdjustment.lua",
		"Code/FUNCTIONS_CombatActions.lua",
		"Code/PROPERTIES_Explosives.lua",
		"Code/PROPERTIES_Unit.lua",
		"Entities/nail_can.lua",
		"Entities/tear_can.lua",
		"Entities/flash_can.lua",
		"Entities/smoke_can.lua",
		"InventoryItem/weapon_shrapnel.lua",
		"Code/FX_Inherit.lua",
		"Code/PlaceObj_FX.lua",
		"InventoryItem/TNTBolt_IED.lua",
		"InventoryItem/TNTBolt_IED_1.lua",
		"InventoryItem/NailBomb_IED.lua",
		"InventoryItem/SmokeGrenade_IED.lua",
		"InventoryItem/Molotov.lua",
		"InventoryItem/Pipe_IED.lua",
		"InventoryItem/PipeBomb.lua",
		"InventoryItem/Warhead_Frag_IED.lua",
		"InventoryItem/TearGasGrenade_IED.lua",
		"InventoryItem/ConcussiveGrenade_IED.lua",
		"InventoryItem/HE_Grenade_1.lua",
		"InventoryItem/IncendiaryGrenade.lua",
		"InventoryItem/_40mmFlashbangGrenade.lua",
		"InventoryItem/_40mmFragGrenade.lua",
		"InventoryItem/Warhead_Frag.lua",
		"InventoryItem/MortarShell_Gas.lua",
		"InventoryItem/MortarShell_HE.lua",
		"InventoryItem/MortarShell_Smoke.lua",
		"InventoryItem/ConcussiveGrenade.lua",
		"InventoryItem/TearGasGrenade.lua",
		"InventoryItem/TNT.lua",
		"InventoryItem/ShapedCharge.lua",
		"InventoryItem/HE_Grenade.lua",
		"InventoryItem/ProximityC4.lua",
		"InventoryItem/ProximityPETN.lua",
		"InventoryItem/ProximityTNT.lua",
		"InventoryItem/TimedC4.lua",
		"InventoryItem/TimedPETN.lua",
		"InventoryItem/TimedTNT.lua",
		"InventoryItem/RemoteC4.lua",
		"InventoryItem/RemotePETN.lua",
		"InventoryItem/RemoteTNT.lua",
		"InventoryItem/Super_HE_Grenade.lua",
		"InventoryItem/FlareStick.lua",
		"InventoryItem/GlowStick.lua",
		"InventoryItem/SmokeGrenade.lua",
		"InventoryItem/ToxicGasGrenade.lua",
		"InventoryItem/BlackPowder.lua",
		"InventoryItem/C4.lua",
		"InventoryItem/FragGrenade.lua",
		"InventoryItem/PETN.lua",
	},
	'default_options', {
		deviate_stat = "Dexterity/Explosives",
		enabled_bounce = true,
		enabled_bounce_pred = true,
		grenade_throw_diff = "Normal (0)",
		mishap_option = "60 (default)",
	},
	'has_data', true,
	'saved', 1713506306,
	'code_hash', 8785772746992767523,
	'affected_resources', {
		PlaceObj('ModResourcePreset', {
			'Class', "CharacterEffectCompositeDef",
			'Id', "cancel_shot_flashbang",
			'ClassDisplayName', "Character effect",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "CharacterEffectCompositeDef",
			'Id', "dazed_flashbang",
			'ClassDisplayName', "Character effect",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "InventoryItemCompositeDef",
			'Id', "weapon_shrapnel",
			'ClassDisplayName', "Inventory item",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "ActionFXObject",
			'Id', "mwoiOav_",
			'ClassDisplayName', "ActionFX Object",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "ActionFXObject",
			'Id', "3YQdpAfz",
			'ClassDisplayName', "ActionFX Object",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "ActionFXObject",
			'Id', "K8Qy_JDY",
			'ClassDisplayName', "ActionFX Object",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "ActionFXParticles",
			'Id', "EkRCa1g6",
			'ClassDisplayName', "ActionFX Particles",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "ActionFXObject",
			'Id', "bBo7O2vQ",
			'ClassDisplayName', "ActionFX Object",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "ActionFXObject",
			'Id', "YmH6IxkH",
			'ClassDisplayName', "ActionFX Object",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "ActionFXParticles",
			'Id', "NzCxQfx-",
			'ClassDisplayName', "ActionFX Particles",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "ActionFXParticles",
			'Id', "tFubTyTu",
			'ClassDisplayName', "ActionFX Particles",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "ActionFXParticles",
			'Id', "R-7C51GE",
			'ClassDisplayName', "ActionFX Particles",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "ActionFXObject",
			'Id', "uvI7IVhL",
			'ClassDisplayName', "ActionFX Object",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "ActionFXObject",
			'Id', "l0V-TW9J",
			'ClassDisplayName', "ActionFX Object",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "ActionFXObject",
			'Id', "Gopwg9SS",
			'ClassDisplayName', "ActionFX Object",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "ActionFXObject",
			'Id', "QTMDxdo6",
			'ClassDisplayName', "ActionFX Object",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "ActionFXParticles",
			'Id', "ORWlPyss",
			'ClassDisplayName', "ActionFX Particles",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "InventoryItemCompositeDef",
			'Id', "TNTBolt_IED",
			'ClassDisplayName', "Inventory item",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "InventoryItemCompositeDef",
			'Id', "TNTBolt_IED_1",
			'ClassDisplayName', "Inventory item",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "InventoryItemCompositeDef",
			'Id', "NailBomb_IED",
			'ClassDisplayName', "Inventory item",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "InventoryItemCompositeDef",
			'Id', "SmokeGrenade_IED",
			'ClassDisplayName', "Inventory item",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "InventoryItemCompositeDef",
			'Id', "Molotov",
			'ClassDisplayName', "Inventory item",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "InventoryItemCompositeDef",
			'Id', "Pipe_IED",
			'ClassDisplayName', "Inventory item",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "InventoryItemCompositeDef",
			'Id', "PipeBomb",
			'ClassDisplayName', "Inventory item",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "InventoryItemCompositeDef",
			'Id', "Warhead_Frag_IED",
			'ClassDisplayName', "Inventory item",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "InventoryItemCompositeDef",
			'Id', "TearGasGrenade_IED",
			'ClassDisplayName', "Inventory item",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "InventoryItemCompositeDef",
			'Id', "ConcussiveGrenade_IED",
			'ClassDisplayName', "Inventory item",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "InventoryItemCompositeDef",
			'Id', "HE_Grenade_1",
			'ClassDisplayName', "Inventory item",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "InventoryItemCompositeDef",
			'Id', "IncendiaryGrenade",
			'ClassDisplayName', "Inventory item",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "InventoryItemCompositeDef",
			'Id', "_40mmFlashbangGrenade",
			'ClassDisplayName', "Inventory item",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "InventoryItemCompositeDef",
			'Id', "_40mmFragGrenade",
			'ClassDisplayName', "Inventory item",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "InventoryItemCompositeDef",
			'Id', "Warhead_Frag",
			'ClassDisplayName', "Inventory item",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "InventoryItemCompositeDef",
			'Id', "MortarShell_Gas",
			'ClassDisplayName', "Inventory item",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "InventoryItemCompositeDef",
			'Id', "MortarShell_HE",
			'ClassDisplayName', "Inventory item",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "InventoryItemCompositeDef",
			'Id', "MortarShell_Smoke",
			'ClassDisplayName', "Inventory item",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "InventoryItemCompositeDef",
			'Id', "ConcussiveGrenade",
			'ClassDisplayName', "Inventory item",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "InventoryItemCompositeDef",
			'Id', "TearGasGrenade",
			'ClassDisplayName', "Inventory item",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "InventoryItemCompositeDef",
			'Id', "TNT",
			'ClassDisplayName', "Inventory item",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "InventoryItemCompositeDef",
			'Id', "ShapedCharge",
			'ClassDisplayName', "Inventory item",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "InventoryItemCompositeDef",
			'Id', "HE_Grenade",
			'ClassDisplayName', "Inventory item",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "InventoryItemCompositeDef",
			'Id', "ProximityC4",
			'ClassDisplayName', "Inventory item",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "InventoryItemCompositeDef",
			'Id', "ProximityPETN",
			'ClassDisplayName', "Inventory item",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "InventoryItemCompositeDef",
			'Id', "ProximityTNT",
			'ClassDisplayName', "Inventory item",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "InventoryItemCompositeDef",
			'Id', "TimedC4",
			'ClassDisplayName', "Inventory item",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "InventoryItemCompositeDef",
			'Id', "TimedPETN",
			'ClassDisplayName', "Inventory item",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "InventoryItemCompositeDef",
			'Id', "TimedTNT",
			'ClassDisplayName', "Inventory item",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "InventoryItemCompositeDef",
			'Id', "RemoteC4",
			'ClassDisplayName', "Inventory item",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "InventoryItemCompositeDef",
			'Id', "RemotePETN",
			'ClassDisplayName', "Inventory item",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "InventoryItemCompositeDef",
			'Id', "RemoteTNT",
			'ClassDisplayName', "Inventory item",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "InventoryItemCompositeDef",
			'Id', "Super_HE_Grenade",
			'ClassDisplayName', "Inventory item",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "InventoryItemCompositeDef",
			'Id', "FlareStick",
			'ClassDisplayName', "Inventory item",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "InventoryItemCompositeDef",
			'Id', "GlowStick",
			'ClassDisplayName', "Inventory item",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "InventoryItemCompositeDef",
			'Id', "SmokeGrenade",
			'ClassDisplayName', "Inventory item",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "InventoryItemCompositeDef",
			'Id', "ToxicGasGrenade",
			'ClassDisplayName', "Inventory item",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "InventoryItemCompositeDef",
			'Id', "BlackPowder",
			'ClassDisplayName', "Inventory item",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "InventoryItemCompositeDef",
			'Id', "C4",
			'ClassDisplayName', "Inventory item",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "InventoryItemCompositeDef",
			'Id', "FragGrenade",
			'ClassDisplayName', "Inventory item",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "InventoryItemCompositeDef",
			'Id', "PETN",
			'ClassDisplayName', "Inventory item",
		}),
	},
})