return PlaceObj('ModDef', {
	'title', "Rato's Explosive Overhaul 2.0",
	'description', "[b]Disclaimer: This mod can be very perfomance hungry[/b]\n\nThis mod is dedicated to Toni.\n\n[h1]Features:[/h1]\n\n[b]Reworked Mishap System[/b]: Throwing a grenade now involves a skill check. The worse the skill check, the greater the deviation. Distance increases the difficulty of the check. This change is granular and dimensional, moving away from the previous all-or-nothing approach. No more pixel perfect grenades. Applies to all explosives except Mortars, which keep the old mishap system\n\n[b]Grenade Bouncing[/b]: Grenades now bounce off surfaces with realistic physical simulation. Factors such as throw speed, grenade shape, weight, surface impact, and angle of trajectory all affect the bounce.\n\n[b]Simulated Shrapnel[/b]: Each piece of grenade shrapnel is individually simulated, enhancing the realism of explosions. Shrapnel has no armor penetration and can cause bleeding and other status effects when it hits a bodypart. Be aware that the shrapnel damage, being dynamic, will not be shown at the damage portion of the grenade. High shrapnel grenades will do about +25/+35 dmg to unarmored enemies inside the primary blast radius\n\n[b]Improvised Explosive Devices (IEDs)[/b]: (Most) Crafted explosives are now classified as IEDs with a chance of malfunction. Malfunctions can result in the grenade being inert, timed, or proximity-based, and the player won't know which until it happens. The malfunction chance is determined by the crafting unit's explosive skill. Optional. Legion and Thugs will mostly use IED explosives\n\n[b]New Explosives[/b] -\nIEDS: Nail Bomb, Fragmentary TNT Stick, Smoke and Tear Gas Can Grenades, Improvised Flashbang\nOther: High Explosive (MK3) grenade, Incendiary Grenade\n\n[b]Other Changes[/b]:\nAI will correctly compensate simple bounces. Does not conflict with AI mods.\nHand explosives range is sligthly increased.\nFlashbangs will cause the dazed (-40% cth), supress, and cancel readied attacks.\nExplosive Skill no longer increases the damage of the grenade.\nMod options to manipulate Explosives damage, throw difficulty and more.\n\nif you want to buy me a coffee you can do so here:\nhttps://www.buymeacoffee.com/rato_modder\n\nFeedback is highly appreciated, balance is WIP",
	'image', "Mod/RATONADE/Images/preview.JPG",
	'last_changes', "2.0",
	'id', "RATONADE",
	'author', "rato",
	'version_major', 2,
	'version', 3560,
	'lua_revision', 233360,
	'saved_with_revision', 350233,
	'entities', {
		"frag_tnt_misfired",
		"fragmentary_tnt",
		"smoke_can",
		"flash_can",
		"tear_can",
		"nail_can",
	},
	'code', {
		"CharacterEffect/cancel_shot_flashbang.lua",
		"CharacterEffect/dazed_flashbang.lua",
		"Code/____init_globals.lua",
		"Code/SOURCE_CalcBounceParabola_LUA.lua",
		"Code/SOURCE_SectorOperations_CraftCommonBase_Tick.lua",
		"Code/SOURCE_AnimGrenadeTraj.lua",
		"Code/SOURCE_GrenadeGetAttackResults.lua",
		"Code/SOURCE_ApplyExplosionDamage.lua",
		"Code/SOURCE_HeavyWeaponsGetAttackResults.lua",
		"Code/SOURCE_ThrowableTrapOnLand.lua",
		"Code/SOURCE_GrenadeOnLand.lua",
		"Code/SOURCE_UnitThrowGrenade.lua",
		"Code/SOURCE_GrenadeGetTrajectory.lua",
		"Code/SOURCE_GetGrenadeBonusDamage.lua",
		"Code/SOURCE_GrenadeCalcTrajectory.lua",
		"Code/SOURCE_CombatActionGrenadeDescription.lua",
		"Code/SOURCE_FormatMishapChance.lua",
		"Code/SOURCE_SetAPIndicator.lua",
		"Code/SOURCE_LandmineFunctions.lua",
		"Code/SOURCE_MergeAndSplitIED.lua",
		"Code/FUNCTIONS_BounceGrenade.lua",
		"Code/FUNCTIONS_IEDlootRules.lua",
		"Code/FUNCTIONS_DynamicSpawnLandmine_MisfiredIED.lua",
		"Code/FUNCTIONS_DeviateGrenade.lua",
		"Code/FUNCTIONS_RatonadeBounceCalcTrajectory.lua",
		"Code/FUNCTIONS_BounceObjMaterialSpeed.lua",
		"Code/FUNCTIONS_processIEDmisfire.lua",
		"Code/FUNCTIONS_Debug.lua",
		"Code/FUNCTIONS_Shrapnel.lua",
		"Code/FUNCTIONS_Shrapnel_VectorGenerators.lua",
		"Code/FUNCTIONS_Util.lua",
		"Code/FUNCTIONS_processExplosiveHitEffects.lua",
		"Code/FUNCTIONS_ItemChanges.lua",
		"Code/FUNCTIONS_AIAdjustment.lua",
		"Code/FUNCTIONS_AlterExternalItems.lua",
		"Code/FUNCTIONS_DetermineIEDMisfireChance_Craft.lua",
		"Code/DESCRIPTION_HINTS.lua",
		"Code/PROPERTIES_Explosives.lua",
		"Code/PROPERTIES_Landmine.lua",
		"Code/PROPERTIES_Unit.lua",
		"Code/PROPERTIES_InventoryStack.lua",
		"Code/PATCH.lua",
		"Code/PATCH_call.lua",
		"Code/FX_PlaceObj.lua",
		"Code/FX_Inherit.lua",
		"Code/FX_DefineVisualClass.lua",
		"InventoryItem/weapon_shrapnel.lua",
		"Entities/frag_tnt_misfired.lua",
		"Entities/fragmentary_tnt.lua",
		"Entities/smoke_can.lua",
		"Entities/flash_can.lua",
		"Entities/tear_can.lua",
		"Entities/nail_can.lua",
		"InventoryItem/TNTBolt_IED.lua",
		"InventoryItem/NailBomb_IED.lua",
		"InventoryItem/SmokeGrenade_IED.lua",
		"InventoryItem/TearGasGrenade_IED.lua",
		"InventoryItem/ConcussiveGrenade_IED.lua",
		"InventoryItem/IncendiaryGrenade.lua",
		"InventoryItem/HE_Grenade_1.lua",
	},
	'default_options', {
		AI_skill_throw_diff = "Normal (0)",
		GL_throw_diff = "Normal (0)",
		RPG_throw_diff = "Normal (0)",
		deviate_stat = "Dexterity/Explosives",
		deviate_stat_GL = "Marksmanship/Explosives",
		deviate_stat_RPG = "Strength/Explosives",
		disable_IED_craftRules = false,
		enabled_bounce = true,
		enabled_bounce_pred = true,
		explosive_dmg = "100",
		grenade_throw_diff = "Normal (0)",
		mifire_chance_mul = "100",
		shrap_dmg = "100",
		shrap_eff_chance = "100",
		shrap_num = "100",
	},
	'has_data', true,
	'saved', 1716588027,
	'code_hash', 5104574777640651986,
	'affected_resources', {
		PlaceObj('ModResourcePreset', {
			'Class', "CharacterEffectCompositeDef",
			'Id', "cancel_shot_flashbang",
			'ClassDisplayName', "Character effect",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "CharacterEffectCompositeDef",
			'Id', "dazed_flashbang",
			'ClassDisplayName', "Character effect",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "InventoryItemCompositeDef",
			'Id', "weapon_shrapnel",
			'ClassDisplayName', "Inventory item",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "CraftOperationsRecipeDef",
			'Id', "CraftNailBombIED",
			'ClassDisplayName', "Crafting operation recipe",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "CraftOperationsRecipeDef",
			'Id', "He_grenade_craft_1",
			'ClassDisplayName', "Crafting operation recipe",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "CraftOperationsRecipeDef",
			'Id', "CraftTNTFragIED",
			'ClassDisplayName', "Crafting operation recipe",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "CraftOperationsRecipeDef",
			'Id', "CraftIncendiaryGrenade",
			'ClassDisplayName', "Crafting operation recipe",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "CraftOperationsRecipeDef",
			'Id', "CraftSmokeIED",
			'ClassDisplayName', "Crafting operation recipe",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "CraftOperationsRecipeDef",
			'Id', "CraftTearGasIED",
			'ClassDisplayName', "Crafting operation recipe",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "CraftOperationsRecipeDef",
			'Id', "CraftFlashbangIED",
			'ClassDisplayName', "Crafting operation recipe",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "ActionFXObject",
			'Id', "mwoiOav_",
			'ClassDisplayName', "ActionFX Object",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "ActionFXObject",
			'Id', "3YQdpAfz",
			'ClassDisplayName', "ActionFX Object",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "ActionFXObject",
			'Id', "K8Qy_JDY",
			'ClassDisplayName', "ActionFX Object",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "ActionFXParticles",
			'Id', "EkRCa1g6",
			'ClassDisplayName', "ActionFX Particles",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "ActionFXObject",
			'Id', "bBo7O2vQ",
			'ClassDisplayName', "ActionFX Object",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "ActionFXObject",
			'Id', "YmH6IxkH",
			'ClassDisplayName', "ActionFX Object",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "ActionFXParticles",
			'Id', "NzCxQfx-",
			'ClassDisplayName', "ActionFX Particles",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "ActionFXParticles",
			'Id', "tFubTyTu",
			'ClassDisplayName', "ActionFX Particles",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "ActionFXParticles",
			'Id', "R-7C51GE",
			'ClassDisplayName', "ActionFX Particles",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "ActionFXObject",
			'Id', "uvI7IVhL",
			'ClassDisplayName', "ActionFX Object",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "ActionFXObject",
			'Id', "l0V-TW9J",
			'ClassDisplayName', "ActionFX Object",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "ActionFXObject",
			'Id', "Gopwg9SS",
			'ClassDisplayName', "ActionFX Object",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "ActionFXObject",
			'Id', "tq7Inev-",
			'ClassDisplayName', "ActionFX Object",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "ActionFXObject",
			'Id', "0-jiTofE",
			'ClassDisplayName', "ActionFX Object",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "ActionFXObject",
			'Id', "IwSIcixg",
			'ClassDisplayName', "ActionFX Object",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "ActionFXObject",
			'Id', "AcHQN0Ff",
			'ClassDisplayName', "ActionFX Object",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "ActionFXObject",
			'Id', "qLAsLR2x",
			'ClassDisplayName', "ActionFX Object",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "ActionFXObject",
			'Id', "bk0RbORD",
			'ClassDisplayName', "ActionFX Object",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "ActionFXObject",
			'Id', "QTMDxdo6",
			'ClassDisplayName', "ActionFX Object",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "ActionFXParticles",
			'Id', "ORWlPyss",
			'ClassDisplayName', "ActionFX Particles",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "InventoryItemCompositeDef",
			'Id', "TNTBolt_IED",
			'ClassDisplayName', "Inventory item",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "InventoryItemCompositeDef",
			'Id', "NailBomb_IED",
			'ClassDisplayName', "Inventory item",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "InventoryItemCompositeDef",
			'Id', "SmokeGrenade_IED",
			'ClassDisplayName', "Inventory item",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "InventoryItemCompositeDef",
			'Id', "TearGasGrenade_IED",
			'ClassDisplayName', "Inventory item",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "InventoryItemCompositeDef",
			'Id', "ConcussiveGrenade_IED",
			'ClassDisplayName', "Inventory item",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "InventoryItemCompositeDef",
			'Id', "IncendiaryGrenade",
			'ClassDisplayName', "Inventory item",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "InventoryItemCompositeDef",
			'Id', "HE_Grenade_1",
			'ClassDisplayName', "Inventory item",
		}),
	},
	'steam_id', "3253652174",
})