-- ========== THIS IS AN AUTOMATICALLY GENERATED FILE! ==========

function RatoEO_Patch()
	print("Running RatoEO_Patch ...")
	FragGrenade.ID = "FragGrenade"
	FragGrenade.AttackAP = 6000
	FragGrenade.BaseDamage = 29
	FragGrenade.r_shrap_num = 350
	FragGrenade.AreaOfEffect = 3
	FragGrenade.ThrowMaxRange = 19
	FragGrenade.BaseRange = 8
	FragGrenade.PenetrationClass = 4
	FragGrenade.is_ied = false
	FragGrenade.r_concussive_force = 3
	FragGrenade.r_mass = 540
	FragGrenade.Weigth = 540
	FragGrenade.r_timer = 6500
	FragGrenade.r_shape = "Stick_like"
	FragGrenade.CanBounce = true
	FragGrenade.r_soft_surface = false
	FragGrenade.CanAppearInShop = true
	FragGrenade.AdditionalHint = T( 470605372277,[[<EO_description_hints>
]])
	FragGrenade.Cost = 600
	FragGrenade.RestockWeight = 70
	HE_Grenade.ID = "HE_Grenade"
	HE_Grenade.DisplayName = T(133482406191, "Fragmentary Grenade")
	HE_Grenade.DisplayNamePlural = T(652922900362, "Fragmentary Grenades")
	HE_Grenade.AttackAP = 6000
	HE_Grenade.BaseDamage = 29
	HE_Grenade.r_shrap_num = 700
	HE_Grenade.AreaOfEffect = 3
	HE_Grenade.ThrowMaxRange = 18
	HE_Grenade.BaseRange = 7
	HE_Grenade.PenetrationClass = 4
	HE_Grenade.is_ied = false
	HE_Grenade.r_concussive_force = 3
	HE_Grenade.r_mass = 570
	HE_Grenade.Weigth = 570
	HE_Grenade.r_timer = 4500
	HE_Grenade.r_shape = "Spherical"
	HE_Grenade.DisplayName = T(133482406191, "Fragmentary Grenade")
	HE_Grenade.CanBounce = true
	HE_Grenade.r_soft_surface = false
	HE_Grenade.CanAppearInShop = true
	HE_Grenade.AdditionalHint = T( 874992284715,[[<EO_description_hints>
]])
	HE_Grenade.Cost = 800
	HE_Grenade.RestockWeight = 60
	HE_Grenade_1.ID = "HE_Grenade_1"
	HE_Grenade_1.AttackAP = 6000
	HE_Grenade_1.BaseDamage = 36
	HE_Grenade_1.r_shrap_num = 350
	HE_Grenade_1.AreaOfEffect = 3
	HE_Grenade_1.ThrowMaxRange = 18
	HE_Grenade_1.BaseRange = 7
	HE_Grenade_1.PenetrationClass = 5
	HE_Grenade_1.is_ied = false
	HE_Grenade_1.r_concussive_force = 4
	HE_Grenade_1.r_mass = 400
	HE_Grenade_1.Weigth = 400
	HE_Grenade_1.r_timer = 4500
	HE_Grenade_1.r_shape = "Cylindrical"
	HE_Grenade_1.CanBounce = true
	HE_Grenade_1.r_soft_surface = false
	HE_Grenade_1.CanAppearInShop = true
	HE_Grenade_1.Cost = 1000
	HE_Grenade_1.Tier = 2
	HE_Grenade_1.RestockWeight = 30
	HE_Grenade_1.PocketL_amount = 4
	HE_Grenade_1.PocketML_amount = 2
	HE_Grenade_1.PocketM_amount = 1
	ShapedCharge.ID = "ShapedCharge"
	ShapedCharge.AttackAP = 6000
	ShapedCharge.BaseDamage = 37
	ShapedCharge.r_shrap_num = 350
	ShapedCharge.AreaOfEffect = 8
	ShapedCharge.ThrowMaxRange = 14
	ShapedCharge.BaseRange = 4
	ShapedCharge.PenetrationClass = 4
	ShapedCharge.is_ied = false
	ShapedCharge.r_concussive_force = 3
	ShapedCharge.r_mass = 1070
	ShapedCharge.Weigth = 1070
	ShapedCharge.r_shape = "Stick_like"
	ShapedCharge.CanBounce = false
	ShapedCharge.r_soft_surface = false
	ShapedCharge.CanAppearInShop = false
	ShapedCharge.AdditionalHint = T( 921753015061,[[<EO_description_hints>
<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Cone-shaped explosion
<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Very low accuracy when used by anyone except Barry]])
	ShapedCharge.Cost = 2250
	ShapedCharge.RestockWeight = 60
	PipeBomb.ID = "PipeBomb"
	PipeBomb.AttackAP = 4000
	PipeBomb.r_shrap_num = 240
	PipeBomb.ThrowMaxRange = 14
	PipeBomb.BaseRange = 4
	PipeBomb.is_ied = true
	PipeBomb.r_concussive_force = 3
	PipeBomb.r_mass = 980
	PipeBomb.Weigth = 980
	PipeBomb.r_shape = "Long"
	PipeBomb.CanBounce = true
	PipeBomb.r_soft_surface = false
	PipeBomb.CanAppearInShop = false
	PipeBomb.AdditionalHint = T( 329802605732,[[<EO_description_hints>
<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Explodes after 1 turn (or 5 seconds out of combat)]])
	PipeBomb.Cost = 450
	NailBomb_IED.ID = "NailBomb_IED"
	NailBomb_IED.AttackAP = 6000
	NailBomb_IED.BaseDamage = 18
	NailBomb_IED.r_shrap_num = 680
	NailBomb_IED.AreaOfEffect = 3
	NailBomb_IED.ThrowMaxRange = 18
	NailBomb_IED.BaseRange = 7
	NailBomb_IED.PenetrationClass = 3
	NailBomb_IED.is_ied = true
	NailBomb_IED.r_concussive_force = 1
	NailBomb_IED.r_mass = 400
	NailBomb_IED.Weigth = 400
	NailBomb_IED.r_timer = 3000
	NailBomb_IED.r_shape = "Can"
	NailBomb_IED.CanBounce = true
	NailBomb_IED.r_soft_surface = false
	NailBomb_IED.CanAppearInShop = false
	NailBomb_IED.Cost = 300
	NailBomb_IED.PocketL_amount = 4
	NailBomb_IED.PocketML_amount = 2
	NailBomb_IED.PocketM_amount = 1
	TNTBolt_IED.ID = "TNTBolt_IED"
	TNTBolt_IED.AttackAP = 7000
	TNTBolt_IED.BaseDamage = 35
	TNTBolt_IED.r_shrap_num = 300
	TNTBolt_IED.AreaOfEffect = 3
	TNTBolt_IED.ThrowMaxRange = 14
	TNTBolt_IED.BaseRange = 4
	TNTBolt_IED.PenetrationClass = 4
	TNTBolt_IED.is_ied = true
	TNTBolt_IED.r_concussive_force = 4
	TNTBolt_IED.r_mass = 700
	TNTBolt_IED.Weigth = 700
	TNTBolt_IED.r_timer = 3500
	TNTBolt_IED.r_shape = "Long"
	TNTBolt_IED.CanBounce = true
	TNTBolt_IED.r_soft_surface = true
	TNTBolt_IED.CanAppearInShop = false
	TNTBolt_IED.Cost = 400
	TNTBolt_IED.PocketL_amount = 3
	TNTBolt_IED.PocketML_amount = 1
	TNTBolt_IED.PocketM_amount = 1
	TearGasGrenade.ID = "TearGasGrenade"
	TearGasGrenade.AttackAP = 4000
	TearGasGrenade.ThrowMaxRange = 18
	TearGasGrenade.BaseRange = 7
	TearGasGrenade.is_ied = false
	TearGasGrenade.r_mass = 500
	TearGasGrenade.Weigth = 500
	TearGasGrenade.r_timer = 4000
	TearGasGrenade.r_shape = "Cylindrical"
	TearGasGrenade.CanBounce = true
	TearGasGrenade.r_soft_surface = false
	TearGasGrenade.CanAppearInShop = true
	TearGasGrenade.AdditionalHint = T( 961521854617,[[<EO_description_hints>
<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Inflicts <color EmStyle>Blinded</color>
<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Ranged attacks passing through gas become <color EmStyle>grazing</color> hits
<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> No damage
<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Almost silent]])
	TearGasGrenade.Cost = 1200
	TearGasGrenade.RestockWeight = 17
	TearGasGrenade_IED.ID = "TearGasGrenade_IED"
	TearGasGrenade_IED.AttackAP = 4000
	TearGasGrenade_IED.ThrowMaxRange = 17
	TearGasGrenade_IED.BaseRange = 7
	TearGasGrenade_IED.is_ied = true
	TearGasGrenade_IED.r_mass = 600
	TearGasGrenade_IED.Weigth = 600
	TearGasGrenade_IED.r_timer = 3500
	TearGasGrenade_IED.r_shape = "Can"
	TearGasGrenade_IED.CanBounce = true
	TearGasGrenade_IED.r_soft_surface = false
	TearGasGrenade_IED.CanAppearInShop = false
	TearGasGrenade_IED.Cost = 600
	TearGasGrenade_IED.RestockWeight = 17
	TearGasGrenade_IED.PocketL_amount = 4
	TearGasGrenade_IED.PocketML_amount = 2
	TearGasGrenade_IED.PocketM_amount = 1
	ConcussiveGrenade.ID = "ConcussiveGrenade"
	ConcussiveGrenade.AttackAP = 4000
	ConcussiveGrenade.AreaOfEffect = 3
	ConcussiveGrenade.ThrowMaxRange = 20
	ConcussiveGrenade.BaseRange = 9
	ConcussiveGrenade.is_ied = false
	ConcussiveGrenade.r_mass = 390
	ConcussiveGrenade.Weigth = 390
	ConcussiveGrenade.r_timer = 3000
	ConcussiveGrenade.r_shape = "Cylindrical"
	ConcussiveGrenade.CanBounce = true
	ConcussiveGrenade.r_soft_surface = false
	ConcussiveGrenade.CanAppearInShop = true
	ConcussiveGrenade.AdditionalHint = T( 998632651224,[[<EO_description_hints>
<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Causes <color EmStyle>Suppressed</color>
<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Causes <color EmStyle>Dazed</color>
<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Cancel readied attacks
<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Very loud. That's the point of this grenade]])
	ConcussiveGrenade.Cost = 1200
	ConcussiveGrenade.RestockWeight = 17
	ConcussiveGrenade_IED.ID = "ConcussiveGrenade_IED"
	ConcussiveGrenade_IED.AttackAP = 4000
	ConcussiveGrenade_IED.AreaOfEffect = 3
	ConcussiveGrenade_IED.ThrowMaxRange = 17
	ConcussiveGrenade_IED.BaseRange = 6
	ConcussiveGrenade_IED.is_ied = true
	ConcussiveGrenade_IED.r_mass = 600
	ConcussiveGrenade_IED.Weigth = 600
	ConcussiveGrenade_IED.r_timer = 3000
	ConcussiveGrenade_IED.r_shape = "Long"
	ConcussiveGrenade_IED.CanBounce = true
	ConcussiveGrenade_IED.r_soft_surface = false
	ConcussiveGrenade_IED.CanAppearInShop = false
	ConcussiveGrenade_IED.Cost = 600
	ConcussiveGrenade_IED.RestockWeight = 17
	ConcussiveGrenade_IED.PocketL_amount = 4
	ConcussiveGrenade_IED.PocketML_amount = 2
	ConcussiveGrenade_IED.PocketM_amount = 1
	SmokeGrenade.ID = "SmokeGrenade"
	SmokeGrenade.AttackAP = 4000
	SmokeGrenade.ThrowMaxRange = 18
	SmokeGrenade.BaseRange = 7
	SmokeGrenade.is_ied = false
	SmokeGrenade.r_mass = 500
	SmokeGrenade.Weigth = 500
	SmokeGrenade.r_timer = 3500
	SmokeGrenade.r_shape = "Cylindrical"
	SmokeGrenade.CanBounce = true
	SmokeGrenade.r_soft_surface = false
	SmokeGrenade.CanAppearInShop = true
	SmokeGrenade.AdditionalHint = T( 109176686173,[[<EO_description_hints>
<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Ranged attacks passing through gas become <color EmStyle>grazing</color> hits
<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> No damage
<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Almost silent]])
	SmokeGrenade.Cost = 900
	SmokeGrenade.RestockWeight = 17
	SmokeGrenade_IED.ID = "SmokeGrenade_IED"
	SmokeGrenade_IED.AttackAP = 4000
	SmokeGrenade_IED.ThrowMaxRange = 17
	SmokeGrenade_IED.BaseRange = 7
	SmokeGrenade_IED.is_ied = true
	SmokeGrenade_IED.r_mass = 600
	SmokeGrenade_IED.Weigth = 600
	SmokeGrenade_IED.r_timer = 3000
	SmokeGrenade_IED.r_shape = "Can"
	SmokeGrenade_IED.CanBounce = true
	SmokeGrenade_IED.r_soft_surface = false
	SmokeGrenade_IED.CanAppearInShop = false
	SmokeGrenade_IED.Cost = 400
	SmokeGrenade_IED.RestockWeight = 17
	SmokeGrenade_IED.PocketL_amount = 4
	SmokeGrenade_IED.PocketML_amount = 2
	SmokeGrenade_IED.PocketM_amount = 1
	IncendiaryGrenade.ID = "IncendiaryGrenade"
	IncendiaryGrenade.AttackAP = 4000
	IncendiaryGrenade.ThrowMaxRange = 18
	IncendiaryGrenade.BaseRange = 7
	IncendiaryGrenade.is_ied = false
	IncendiaryGrenade.r_mass = 500
	IncendiaryGrenade.Weigth = 500
	IncendiaryGrenade.r_timer = 5000
	IncendiaryGrenade.r_shape = "Cylindrical"
	IncendiaryGrenade.CanBounce = true
	IncendiaryGrenade.r_soft_surface = false
	IncendiaryGrenade.CanAppearInShop = true
	IncendiaryGrenade.AdditionalHint = T( 879120196368,[[<EO_description_hints>
<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Sets an area on fire and inflicts <color EmStyle>Burning</color>]])
	IncendiaryGrenade.Cost = 500
	IncendiaryGrenade.RestockWeight = 32
	IncendiaryGrenade.PocketL_amount = 4
	IncendiaryGrenade.PocketML_amount = 2
	IncendiaryGrenade.PocketM_amount = 1
	Molotov.ID = "Molotov"
	Molotov.AttackAP = 5000
	Molotov.AreaOfEffect = 3
	Molotov.ThrowMaxRange = 15
	Molotov.BaseRange = 4
	Molotov.is_ied = false
	Molotov.r_mass = 980
	Molotov.Weigth = 980
	Molotov.r_timer = 7000
	Molotov.r_shape = "Bottle"
	Molotov.CanBounce = false
	Molotov.r_soft_surface = false
	Molotov.CanAppearInShop = false
	Molotov.AdditionalHint = T( 627770660838,[[<EO_description_hints>
<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Sets an area on fire and inflicts <color EmStyle>Burning</color>]])
	Molotov.Cost = 300
	Molotov.RestockWeight = 32
	ToxicGasGrenade.ID = "ToxicGasGrenade"
	ToxicGasGrenade.AttackAP = 4000
	ToxicGasGrenade.ThrowMaxRange = 18
	ToxicGasGrenade.BaseRange = 7
	ToxicGasGrenade.is_ied = false
	ToxicGasGrenade.r_mass = 600
	ToxicGasGrenade.Weigth = 600
	ToxicGasGrenade.r_timer = 4000
	ToxicGasGrenade.r_shape = "Cylindrical"
	ToxicGasGrenade.CanBounce = true
	ToxicGasGrenade.r_soft_surface = false
	ToxicGasGrenade.CanAppearInShop = false
	ToxicGasGrenade.AdditionalHint = T( 838998848652,[[<EO_description_hints>
<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Inflicts <color EmStyle>Choking</color>
 <image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Ranged attacks passing through gas become grazing hits
 <image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Almost silent]])
	ToxicGasGrenade.Cost = 2250
	ProximityC4.ID = "ProximityC4"
	ProximityC4.AttackAP = 7000
	ProximityC4.r_shrap_num = 50
	ProximityC4.is_ied = false
	ProximityC4.r_concussive_force = 4
	ProximityC4.r_mass = 2000
	ProximityC4.Weigth = 2000
	ProximityC4.r_shape = "Brick"
	ProximityC4.CanBounce = true
	ProximityC4.r_soft_surface = true
	ProximityC4.CanAppearInShop = true
	ProximityC4.AdditionalHint = T( 595566565210,[[<EO_description_hints>
<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Explodes when an enemy enters a small area around it]])
	ProximityC4.Cost = 1800
	ProximityC4.RestockWeight = 10
	ProximityPETN.ID = "ProximityPETN"
	ProximityPETN.AttackAP = 7000
	ProximityPETN.r_shrap_num = 50
	ProximityPETN.is_ied = false
	ProximityPETN.r_concussive_force = 4
	ProximityPETN.r_mass = 1800
	ProximityPETN.Weigth = 1800
	ProximityPETN.r_shape = "Brick"
	ProximityPETN.CanBounce = true
	ProximityPETN.r_soft_surface = true
	ProximityPETN.CanAppearInShop = true
	ProximityPETN.AdditionalHint = T( 761444056312,[[<EO_description_hints>
<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Explodes when an enemy enters a small area around it]])
	ProximityPETN.Cost = 2250
	ProximityPETN.RestockWeight = 10
	ProximityTNT.ID = "ProximityTNT"
	ProximityTNT.AttackAP = 7000
	ProximityTNT.r_shrap_num = 50
	ProximityTNT.is_ied = false
	ProximityTNT.r_concussive_force = 4
	ProximityTNT.r_mass = 1500
	ProximityTNT.Weigth = 1500
	ProximityTNT.r_shape = "Long"
	ProximityTNT.CanBounce = true
	ProximityTNT.r_soft_surface = true
	ProximityTNT.CanAppearInShop = true
	ProximityTNT.AdditionalHint = T( 801919412885,[[<EO_description_hints>
<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Explodes when an enemy enters a small area around it]])
	ProximityTNT.Cost = 1275
	ProximityTNT.RestockWeight = 18
	RemoteC4.ID = "RemoteC4"
	RemoteC4.AttackAP = 4000
	RemoteC4.r_shrap_num = 50
	RemoteC4.is_ied = false
	RemoteC4.r_concussive_force = 4
	RemoteC4.r_mass = 2000
	RemoteC4.Weigth = 2000
	RemoteC4.r_shape = "Brick"
	RemoteC4.CanBounce = true
	RemoteC4.r_soft_surface = true
	RemoteC4.CanAppearInShop = true
	RemoteC4.AdditionalHint = T( 291395660699,[[<EO_description_hints>
<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Explodes when triggered by a remote Detonator switch]])
	RemoteC4.Cost = 1200
	RemoteC4.RestockWeight = 10
	RemotePETN.ID = "RemotePETN"
	RemotePETN.AttackAP = 4000
	RemotePETN.r_shrap_num = 50
	RemotePETN.is_ied = false
	RemotePETN.r_concussive_force = 4
	RemotePETN.r_mass = 1800
	RemotePETN.Weigth = 1800
	RemotePETN.r_shape = "Brick"
	RemotePETN.CanBounce = true
	RemotePETN.r_soft_surface = true
	RemotePETN.CanAppearInShop = true
	RemotePETN.AdditionalHint = T( 188364469531,[[<EO_description_hints>
<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Explodes when triggered by a remote Detonator switch]])
	RemotePETN.Cost = 1200
	RemotePETN.RestockWeight = 10
	RemoteTNT.ID = "RemoteTNT"
	RemoteTNT.AttackAP = 4000
	RemoteTNT.r_shrap_num = 50
	RemoteTNT.is_ied = false
	RemoteTNT.r_concussive_force = 4
	RemoteTNT.r_mass = 1500
	RemoteTNT.Weigth = 1500
	RemoteTNT.r_shape = "Long"
	RemoteTNT.CanBounce = true
	RemoteTNT.r_soft_surface = true
	RemoteTNT.CanAppearInShop = true
	RemoteTNT.AdditionalHint = T( 745627851228,[[<EO_description_hints>
<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Explodes when triggered by a remote Detonator switch]])
	RemoteTNT.Cost = 900
	RemoteTNT.RestockWeight = 10
	TimedC4.ID = "TimedC4"
	TimedC4.AttackAP = 4000
	TimedC4.r_shrap_num = 50
	TimedC4.is_ied = false
	TimedC4.r_concussive_force = 4
	TimedC4.r_mass = 2000
	TimedC4.Weigth = 2000
	TimedC4.r_shape = "Brick"
	TimedC4.CanBounce = true
	TimedC4.r_soft_surface = true
	TimedC4.CanAppearInShop = true
	TimedC4.AdditionalHint = T( 369065452740,[[<EO_description_hints>
<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Explodes after 1 turn (or 5 seconds out of combat)]])
	TimedC4.Cost = 1800
	TimedC4.RestockWeight = 10
	TimedPETN.ID = "TimedPETN"
	TimedPETN.AttackAP = 4000
	TimedPETN.r_shrap_num = 50
	TimedPETN.is_ied = false
	TimedPETN.r_concussive_force = 4
	TimedPETN.r_mass = 1800
	TimedPETN.Weigth = 1800
	TimedPETN.r_shape = "Brick"
	TimedPETN.CanBounce = true
	TimedPETN.r_soft_surface = true
	TimedPETN.CanAppearInShop = true
	TimedPETN.AdditionalHint = T( 898664650416,[[<EO_description_hints>
<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Explodes after 1 turn (or 5 seconds out of combat)]])
	TimedPETN.Cost = 2250
	TimedPETN.RestockWeight = 10
	TimedTNT.ID = "TimedTNT"
	TimedTNT.AttackAP = 4000
	TimedTNT.r_shrap_num = 50
	TimedTNT.is_ied = false
	TimedTNT.r_concussive_force = 4
	TimedTNT.r_mass = 1500
	TimedTNT.Weigth = 1500
	TimedTNT.r_shape = "Long"
	TimedTNT.CanBounce = true
	TimedTNT.r_soft_surface = true
	TimedTNT.CanAppearInShop = true
	TimedTNT.AdditionalHint = T( 216709470259,[[<EO_description_hints>
<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Explodes after 1 turn (or 5 seconds out of combat)]])
	TimedTNT.Cost = 1275
	TimedTNT.RestockWeight = 18
	FlareStick.ID = "FlareStick"
	FlareStick.AttackAP = 4000
	FlareStick.AreaOfEffect = 4
	FlareStick.ThrowMaxRange = 20
	FlareStick.BaseRange = 9
	FlareStick.is_ied = false
	FlareStick.r_mass = 580
	FlareStick.Weigth = 580
	FlareStick.r_shape = "Long"
	FlareStick.CanBounce = true
	FlareStick.r_soft_surface = false
	FlareStick.CanAppearInShop = true
	FlareStick.AdditionalHint = T( 594356356208,[[<EO_description_hints>
<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Illuminates a large area
<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Silent]])
	FlareStick.Cost = 300
	GlowStick.ID = "GlowStick"
	GlowStick.AttackAP = 2000
	GlowStick.AreaOfEffect = 2
	GlowStick.ThrowMaxRange = 23
	GlowStick.BaseRange = 10
	GlowStick.is_ied = false
	GlowStick.r_mass = 250
	GlowStick.Weigth = 250
	GlowStick.r_shape = "Long"
	GlowStick.CanBounce = true
	GlowStick.r_soft_surface = false
	GlowStick.CanAppearInShop = true
	GlowStick.AdditionalHint = T( 178183390592,[[<EO_description_hints>
<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Illuminates a small area]])
	GlowStick.Cost = 150
	TNT.ID = "TNT"
	TNT.BaseDamage = 44
	TNT.r_soft_surface = false
	TNT.CanAppearInShop = true
	TNT.Cost = 360
	TNT.RestockWeight = 50
	C4.ID = "C4"
	C4.BaseDamage = 48
	C4.r_soft_surface = false
	C4.CanAppearInShop = true
	C4.Cost = 720
	C4.RestockWeight = 30
	PETN.ID = "PETN"
	PETN.BaseDamage = 63
	PETN.r_soft_surface = false
	PETN.CanAppearInShop = true
	PETN.Cost = 900
	PETN.RestockWeight = 30
	BlackPowder.ID = "BlackPowder"
	BlackPowder.BaseDamage = 39
	BlackPowder.r_soft_surface = false
	BlackPowder.CanAppearInShop = true
	BlackPowder.Cost = 480
	_40mmFragGrenade.ID = "_40mmFragGrenade"
	_40mmFragGrenade.BaseDamage = 36
	_40mmFragGrenade.r_shrap_num = 300
	_40mmFragGrenade.PenetrationClass = 4
	_40mmFragGrenade.r_concussive_force = 4
	_40mmFragGrenade.r_soft_surface = false
	_40mmFragGrenade.AdditionalHint = T( 485405106879,[[<EO_description_hints>
]])
	_40mmFragGrenade.Cost = 450
	_40mmFragGrenade.RestockWeight = 30
	Warhead_Frag.ID = "Warhead_Frag"
	Warhead_Frag.BaseDamage = 42
	Warhead_Frag.r_shrap_num = 300
	Warhead_Frag.PenetrationClass = 4
	Warhead_Frag.r_concussive_force = 4
	Warhead_Frag.CanBounce = false
	Warhead_Frag.r_soft_surface = false
	Warhead_Frag.AdditionalHint = T( 234738294075,[[<EO_description_hints>
<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Inflicts Suppressed in the epicenter]])
	Warhead_Frag.Cost = 600
	Warhead_Frag.RestockWeight = 30
	MortarShell_HE.ID = "MortarShell_HE"
	MortarShell_HE.BaseDamage = 37
	MortarShell_HE.r_shrap_num = 300
	MortarShell_HE.PenetrationClass = 4
	MortarShell_HE.r_concussive_force = 4
	MortarShell_HE.CanBounce = false
	MortarShell_HE.r_soft_surface = false
	MortarShell_HE.AdditionalHint = T( 424063551328,[[<EO_description_hints>
]])
	MortarShell_HE.Cost = 450
	MortarShell_HE.RestockWeight = 30
	print("Running RatoEO_Patch Done")
end
