UndefineClass('C4')
DefineClass.C4 = {
	__parents = { "ExplosiveSubstance" },
	__generated_by_class = "ModItemInventoryItemCompositeDef",


	object_class = "ExplosiveSubstance",
	Repairable = false,
	Icon = "UI/Icons/Items/c4",
	DisplayName = T(751572443745, --[[ModItemInventoryItemCompositeDef C4 DisplayName]] "C4"),
	DisplayNamePlural = T(867951071563, --[[ModItemInventoryItemCompositeDef C4 DisplayNamePlural]] "C4"),
	AdditionalHint = T(995022991672, --[[ModItemInventoryItemCompositeDef C4 AdditionalHint]] "<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Combine with a Detonator to create an explosive"),
	UnitStat = "Explosives",
	Cost = 400,
	CanAppearInShop = true,
	Tier = 2,
	RestockWeight = 35,
	CategoryPair = "Components",
	CenterUnitDamageMod = 130,
	CenterObjDamageMod = 500,
	CenterAppliedEffects = {
		"Revealed",
		"KnockDown",
		"Exposed",
		"Bleeding",
		"CancelShot",
		"Suppressed",
		"SeverelySuppressed",
	},
	AreaOfEffect = 2,
	AreaObjDamageMod = 500,
	AreaAppliedEffects = {
		"Revealed",
		"KnockDown",
		"Exposed",
		"Bleeding",
		"CancelShot",
		"Suppressed",
		"SeverelySuppressed",
	},
	DeathType = "BlowUp",
	BaseDamage = 38,
	Noise = 30,
}

