UndefineClass('ConcussiveGrenade_IED')
DefineClass.ConcussiveGrenade_IED = {
	__parents = { "Grenade" },
	__generated_by_class = "ModItemInventoryItemCompositeDef",


	object_class = "Grenade",
	Repairable = false,
	Reliability = 100,
	Icon = "Mod/RATONADE/Images/flash_ied 3.png",
	ItemType = "Grenade",
	DisplayName = T(919480215237, --[[ModItemInventoryItemCompositeDef ConcussiveGrenade_IED DisplayName]] "Improvised Flashbang"),
	DisplayNamePlural = T(462067699032, --[[ModItemInventoryItemCompositeDef ConcussiveGrenade_IED DisplayNamePlural]] "Improvised Flashbangs"),
	AdditionalHint = T(261788256938, --[[ModItemInventoryItemCompositeDef ConcussiveGrenade_IED AdditionalHint]] "<EO_description_hints>\n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Causes <color EmStyle>Suppressed</color>\n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Causes <color EmStyle>Dazed</color>\n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Cancel readied attacks\n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Very loud. That's the point of this grenade"),
	UnitStat = "Explosives",
	Cost = 800,
	CanAppearInShop = true,
	Tier = 2,
	RestockWeight = 25,
	CategoryPair = "Grenade",
	MinMishapChance = -2,
	MaxMishapChance = 18,
	MinMishapRange = 0,
	CenterUnitDamageMod = 0,
	CenterObjDamageMod = 0,
	CenterAppliedEffects = {
		"Suppressed",
		"dazed_flashbang",
		"cancel_shot_flashbang",
	},
	AreaUnitDamageMod = 0,
	AreaObjDamageMod = 0,
	AreaAppliedEffects = {
		"cancel_shot_flashbang",
		"Suppressed",
		"dazed_flashbang",
	},
	PenetrationClass = 1,
	BurnGround = false,
	BaseDamage = 0,
	Scatter = 4,
	AttackAP = 4000,
	InaccurateMaxOffset = 4000,
	Noise = 40,
	Entity = "Weapon_StunGrenadeM84",
	ActionIcon = "UI/Icons/Hud/concussive_grenade",
	r_timer = 3000,
	r_mass = 370,
	r_shape = "Cylindrical",
	is_ied = true,
}

