UndefineClass('ConcussiveGrenade')
DefineClass.ConcussiveGrenade = {
	__parents = { "Grenade" },
	__generated_by_class = "ModItemInventoryItemCompositeDef",


	object_class = "Grenade",
	Repairable = false,
	Reliability = 100,
	Icon = "UI/Icons/Weapons/ConcussiveGrenade",
	ItemType = "Grenade",
	DisplayName = T(121480336412, --[[ModItemInventoryItemCompositeDef ConcussiveGrenade DisplayName]] "Flashbang"),
	DisplayNamePlural = T(350652266241, --[[ModItemInventoryItemCompositeDef ConcussiveGrenade DisplayNamePlural]] "Flashbangs"),
	AdditionalHint = T(340204864818, --[[ModItemInventoryItemCompositeDef ConcussiveGrenade AdditionalHint]] "<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Causes <color EmStyle>Suppressed</color>\n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Causes <color EmStyle>Dazed</color>\n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Cancel readied attacks\n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Very loud. That's the point of this grenade"),
	UnitStat = "Explosives",
	Cost = 800,
	CanAppearInShop = true,
	Tier = 2,
	RestockWeight = 25,
	CategoryPair = "Grenade",
	MinMishapChance = -2,
	MaxMishapChance = 18,
	MinMishapRange = 0,
	CenterUnitDamageMod = 0,
	CenterObjDamageMod = 0,
	CenterAppliedEffects = {
		"cancel_shot_flashbang",
		"Suppressed",
		"dazed_flashbang",
		"KnockDown",
	},
	AreaUnitDamageMod = 0,
	AreaObjDamageMod = 0,
	AreaAppliedEffects = {
		"cancel_shot_flashbang",
		"Suppressed",
		"dazed_flashbang",
	},
	PenetrationClass = 1,
	BurnGround = false,
	BaseDamage = 0,
	Scatter = 4,
	AttackAP = 4000,
	BaseRange = 10,
	ThrowMaxRange = 22,
	InaccurateMaxOffset = 4000,
	Noise = 40,
	Entity = "Weapon_StunGrenadeM84",
	ActionIcon = "UI/Icons/Hud/concussive_grenade",
	r_timer = 3000,
	r_mass = 370,
	r_shape = "Cylindrical",
}

