UndefineClass('FlareStick')
DefineClass.FlareStick = {
	__parents = { "Flare" },
	__generated_by_class = "ModItemInventoryItemCompositeDef",


	object_class = "Flare",
	Repairable = false,
	Reliability = 100,
	Icon = "UI/Icons/Weapons/FlareStick",
	ItemType = "Throwables",
	DisplayName = T(509204256542, --[[ModItemInventoryItemCompositeDef FlareStick DisplayName]] "Flare Stick"),
	DisplayNamePlural = T(784449735534, --[[ModItemInventoryItemCompositeDef FlareStick DisplayNamePlural]] "Flare Sticks"),
	AdditionalHint = T(390050967382, --[[ModItemInventoryItemCompositeDef FlareStick AdditionalHint]] "<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Illuminates a large area\n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> High mishap chance\n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Silent"),
	UnitStat = "Explosives",
	Cost = 200,
	CanAppearInShop = true,
	Tier = 2,
	RestockWeight = 25,
	CategoryPair = "Grenade",
	MinMishapChance = 10,
	MaxMishapChance = 50,
	MaxMishapRange = 6,
	CenterUnitDamageMod = 0,
	CenterObjDamageMod = 0,
	AreaOfEffect = 4,
	AreaUnitDamageMod = 0,
	AreaObjDamageMod = 0,
	PenetrationClass = 1,
	BaseDamage = 0,
	Scatter = 4,
	AttackAP = 4000,
	Noise = 0,
	Entity = "Weapon_MolotovCocktail",
	ActionIcon = "UI/Icons/Hud/flare",
	is_explosive = false,
	r_mass = 580,
	r_shape = "Long",
}

