UndefineClass('FragGrenade')
DefineClass.FragGrenade = {
	__parents = { "Grenade" },
	__generated_by_class = "ModItemInventoryItemCompositeDef",


	object_class = "Grenade",
	Repairable = false,
	Reliability = 100,
	Icon = "UI/Icons/Weapons/Frag Grenade",
	ItemType = "Grenade",
	DisplayName = T(884807926062, --[[ModItemInventoryItemCompositeDef FragGrenade DisplayName]] "Stick Grenade"),
	DisplayNamePlural = T(765773516877, --[[ModItemInventoryItemCompositeDef FragGrenade DisplayNamePlural]] "Stick Grenades"),
	Description = "",
	AdditionalHint = "",
	UnitStat = "Explosives",
	Cost = 400,
	CanAppearInShop = true,
	CategoryPair = "Grenade",
	MinMishapChance = -2,
	MaxMishapChance = 18,
	MinMishapRange = 0,
	MaxMishapRange = 3,
	CenterUnitDamageMod = 130,
	CenterObjDamageMod = 200,
	AreaOfEffect = 2,
	AreaObjDamageMod = 250,
	PenetrationClass = 4,
	DeathType = "BlowUp",
	BaseDamage = 22,
	Scatter = 4,
	BaseRange = 7,
	ThrowMaxRange = 17,
	InaccurateMaxOffset = 3000,
	Entity = "MilitaryCamp_Grenade_01",
	ActionIcon = "UI/Icons/Hud/frag_grenade",
	r_timer = 6500,
	r_mass = 595,
	r_shape = "Stick_like",
	r_shrap_num = 350,
}

