UndefineClass('GlowStick')
DefineClass.GlowStick = {
	__parents = { "Flare" },
	__generated_by_class = "ModItemInventoryItemCompositeDef",


	object_class = "Flare",
	Repairable = false,
	Reliability = 100,
	Icon = "UI/Icons/Weapons/GlowStick",
	ItemType = "Throwables",
	DisplayName = T(613585253014, --[[ModItemInventoryItemCompositeDef GlowStick DisplayName]] "Glow Stick"),
	DisplayNamePlural = T(894985193700, --[[ModItemInventoryItemCompositeDef GlowStick DisplayNamePlural]] "Glow Sticks"),
	AdditionalHint = T(772000348805, --[[ModItemInventoryItemCompositeDef GlowStick AdditionalHint]] "<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Illuminates a small area"),
	UnitStat = "Explosives",
	Cost = 100,
	CanAppearInShop = true,
	Tier = 2,
	RestockWeight = 50,
	CategoryPair = "Grenade",
	MinMishapChance = -2,
	MaxMishapChance = 18,
	MaxMishapRange = 6,
	CenterUnitDamageMod = 0,
	CenterObjDamageMod = 0,
	AreaOfEffect = 2,
	AreaUnitDamageMod = 0,
	AreaObjDamageMod = 0,
	PenetrationClass = 1,
	BaseDamage = 0,
	Scatter = 4,
	AttackAP = 2000,
	BaseRange = 10,
	ThrowMaxRange = 20,
	CanBounce = false,
	Noise = 0,
	Entity = "Weapon_MolotovCocktail",
	ActionIcon = "UI/Icons/Hud/throw_glowstick",
	is_explosive = false,
	r_mass = 270,
	r_shape = "Long",
	ExpirationTurns = 10,
}

