UndefineClass('HE_Grenade')
DefineClass.HE_Grenade = {
	__parents = { "Grenade" },
	__generated_by_class = "ModItemInventoryItemCompositeDef",


	object_class = "Grenade",
	Repairable = false,
	Reliability = 100,
	Icon = "UI/Icons/Weapons/HEGrenade",
	SubIcon = "Mod/TU6SADg/Images/bleed3.png",
	ItemType = "Grenade",
	DisplayName = T(547996004204, --[[ModItemInventoryItemCompositeDef HE_Grenade DisplayName]] "Fragmentation Grenade"),
	DisplayNamePlural = T(440377233591, --[[ModItemInventoryItemCompositeDef HE_Grenade DisplayNamePlural]] "Fragmentation Grenade"),
	Description = T(336775963908, --[[ModItemInventoryItemCompositeDef HE_Grenade Description]] "<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120>Inflicts <color EmStyle>Bleeding</color>"),
	AdditionalHint = "",
	UnitStat = "Explosives",
	Cost = 600,
	CanAppearInShop = true,
	Tier = 2,
	CategoryPair = "Grenade",
	MinMishapChance = -2,
	MaxMishapChance = 18,
	MinMishapRange = 0,
	CenterUnitDamageMod = 130,
	CenterObjDamageMod = 200,
	CenterAppliedEffects = {
		"Bleeding",
	},
	AreaObjDamageMod = 250,
	AreaAppliedEffects = {
		"Bleeding",
	},
	PenetrationClass = 4,
	DeathType = "BlowUp",
	BaseDamage = 35,
	Scatter = 4,
	BaseRange = 8,
	ThrowMaxRange = 19,
	InaccurateMaxOffset = 3000,
	Entity = "MilitaryCamp_Grenade_02",
	ActionIcon = "UI/Icons/Hud/throw_grenade",
	r_timer = 4500,
	r_mass = 600,
	r_shape = "Spherical",
	r_shrap_num = 1000,
}

