UndefineClass('Molotov')
DefineClass.Molotov = {
	__parents = { "Grenade" },
	__generated_by_class = "ModItemInventoryItemCompositeDef",


	object_class = "Grenade",
	Repairable = false,
	Reliability = 100,
	Icon = "UI/Icons/Weapons/Molotov",
	ItemType = "GrenadeFire",
	DisplayName = T(270380819426, --[[ModItemInventoryItemCompositeDef Molotov DisplayName]] "Molotov Cocktail"),
	DisplayNamePlural = T(717638534602, --[[ModItemInventoryItemCompositeDef Molotov DisplayNamePlural]] "Molotov Cocktails"),
	AdditionalHint = T(496178231258, --[[ModItemInventoryItemCompositeDef Molotov AdditionalHint]] "<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Sets an area on fire and inflicts <color EmStyle>Burning</color>\n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> High mishap chance"),
	UnitStat = "Explosives",
	Cost = 300,
	CanAppearInShop = true,
	RestockWeight = 50,
	CategoryPair = "Grenade",
	MinMishapChance = 2,
	MaxMishapChance = 30,
	MinMishapRange = 0,
	CenterUnitDamageMod = 0,
	CenterObjDamageMod = 0,
	AreaUnitDamageMod = 0,
	AreaObjDamageMod = 0,
	PenetrationClass = 1,
	BaseDamage = 0,
	Scatter = 4,
	AttackAP = 4000,
	BaseRange = 4,
	ThrowMaxRange = 12,
	CanBounce = false,
	InaccurateMaxOffset = 4000,
	Noise = 0,
	aoeType = "fire",
	Entity = "Weapon_MolotovCocktail",
	ActionIcon = "UI/Icons/Hud/molotov",
	r_timer = 7000,
	r_mass = 980,
	r_shape = "Bottle",
	is_ied = true,
}

