UndefineClass('ProximityTNT')
DefineClass.ProximityTNT = {
	__parents = { "ThrowableTrapItem" },
	__generated_by_class = "ModItemInventoryItemCompositeDef",


	object_class = "ThrowableTrapItem",
	Repairable = false,
	Reliability = 100,
	Icon = "UI/Icons/Items/proximity_tnt",
	ItemType = "Grenade",
	DisplayName = T(367750793000, --[[ModItemInventoryItemCompositeDef ProximityTNT DisplayName]] "Proximity TNT"),
	DisplayNamePlural = T(977084522969, --[[ModItemInventoryItemCompositeDef ProximityTNT DisplayNamePlural]] "Proximity TNT"),
	AdditionalHint = T(222949275095, --[[ModItemInventoryItemCompositeDef ProximityTNT AdditionalHint]] "<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Explodes when an enemy enters a small area around it\n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> High mishap chance"),
	UnitStat = "Explosives",
	Cost = 850,
	CanAppearInShop = true,
	Tier = 2,
	MaxStock = 1,
	RestockWeight = 20,
	MinMishapChance = 2,
	MaxMishapChance = 30,
	MaxMishapRange = 6,
	AttackAP = 7000,
	BaseRange = 3,
	ThrowMaxRange = 7,
	CanBounce = false,
	Noise = 30,
	Entity = "Explosive_TNT",
	ActionIcon = "UI/Icons/Hud/throw_proximity_explosive",
	r_mass = 1500,
	r_shape = "Long",
	TriggerType = "Proximity",
}

