UndefineClass('RemotePETN')
DefineClass.RemotePETN = {
	__parents = { "ThrowableTrapItem" },
	__generated_by_class = "ModItemInventoryItemCompositeDef",


	object_class = "ThrowableTrapItem",
	Repairable = false,
	Reliability = 100,
	Icon = "UI/Icons/Items/remote_petn",
	ItemType = "Grenade",
	DisplayName = T(706074896022, --[[ModItemInventoryItemCompositeDef RemotePETN DisplayName]] "Remote PETN"),
	DisplayNamePlural = T(637241516535, --[[ModItemInventoryItemCompositeDef RemotePETN DisplayNamePlural]] "Remote PETN"),
	AdditionalHint = T(531287541505, --[[ModItemInventoryItemCompositeDef RemotePETN AdditionalHint]] "<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Explodes when triggered by a remote Detonator switch"),
	UnitStat = "Explosives",
	Cost = 800,
	CanAppearInShop = true,
	Tier = 3,
	MaxStock = 1,
	RestockWeight = 10,
	CategoryPair = "Grenade",
	MinMishapChance = -2,
	MaxMishapChance = 18,
	MaxMishapRange = 6,
	AttackAP = 4000,
	BaseRange = 3,
	ThrowMaxRange = 12,
	CanBounce = false,
	Noise = 30,
	Entity = "Explosive_PETN",
	ActionIcon = "UI/Icons/Hud/throw_remote_explosive",
	r_mass = 1800,
	r_shape = "Brick",
	TriggerType = "Remote",
	ExplosiveType = "PETN",
}

