UndefineClass('RemoteTNT')
DefineClass.RemoteTNT = {
	__parents = { "ThrowableTrapItem" },
	__generated_by_class = "ModItemInventoryItemCompositeDef",


	object_class = "ThrowableTrapItem",
	Repairable = false,
	Reliability = 100,
	Icon = "UI/Icons/Items/remote_tnt",
	ItemType = "Grenade",
	DisplayName = T(983794362389, --[[ModItemInventoryItemCompositeDef RemoteTNT DisplayName]] "Remote TNT"),
	DisplayNamePlural = T(396317563366, --[[ModItemInventoryItemCompositeDef RemoteTNT DisplayNamePlural]] "Remote TNT"),
	AdditionalHint = T(174894704271, --[[ModItemInventoryItemCompositeDef RemoteTNT AdditionalHint]] "<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Explodes when triggered by a remote Detonator switch\n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> High mishap chance"),
	UnitStat = "Explosives",
	Cost = 600,
	CanAppearInShop = true,
	Tier = 2,
	MaxStock = 1,
	RestockWeight = 10,
	CategoryPair = "Grenade",
	MinMishapChance = 2,
	MaxMishapChance = 30,
	MaxMishapRange = 6,
	AttackAP = 4000,
	BaseRange = 3,
	ThrowMaxRange = 12,
	CanBounce = false,
	Noise = 30,
	Entity = "Explosive_TNT",
	ActionIcon = "UI/Icons/Hud/throw_remote_explosive",
	r_mass = 1500,
	r_shape = "Long",
	r_shrap_num = 200,
	TriggerType = "Remote",
}

