UndefineClass('SmokeGrenade')
DefineClass.SmokeGrenade = {
	__parents = { "Grenade" },
	__generated_by_class = "ModItemInventoryItemCompositeDef",


	object_class = "Grenade",
	Repairable = false,
	Reliability = 100,
	Icon = "UI/Icons/Weapons/SmokeGrenade",
	ItemType = "Throwables",
	DisplayName = T(110395037196, --[[ModItemInventoryItemCompositeDef SmokeGrenade DisplayName]] "Smoke Grenade"),
	DisplayNamePlural = T(568709088875, --[[ModItemInventoryItemCompositeDef SmokeGrenade DisplayNamePlural]] "Smoke Grenades"),
	AdditionalHint = T(368187604805, --[[ModItemInventoryItemCompositeDef SmokeGrenade AdditionalHint]] "<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Ranged attacks passing through gas become <color EmStyle>grazing</color> hits\n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> No damage\n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Almost silent"),
	UnitStat = "Explosives",
	Cost = 600,
	CanAppearInShop = true,
	Tier = 2,
	RestockWeight = 25,
	CategoryPair = "Grenade",
	MinMishapChance = -2,
	MaxMishapChance = 18,
	MinMishapRange = 0,
	CenterUnitDamageMod = 0,
	CenterObjDamageMod = 0,
	AreaUnitDamageMod = 0,
	AreaObjDamageMod = 0,
	PenetrationClass = 1,
	BaseDamage = 0,
	Scatter = 4,
	AttackAP = 4000,
	InaccurateMaxOffset = 3000,
	Noise = 0,
	aoeType = "smoke",
	Entity = "Weapon_SmokeGrenade_Test",
	ActionIcon = "UI/Icons/Hud/smoke_grenade",
	r_timer = 3500,
	r_mass = 610,
	r_shape = "Cylindrical",
}

