UndefineClass('SmokeGrenade_IED')
DefineClass.SmokeGrenade_IED = {
	__parents = { "Grenade" },
	__generated_by_class = "ModItemInventoryItemCompositeDef",


	object_class = "Grenade",
	Repairable = false,
	Reliability = 100,
	Icon = "Mod/RATONADE/Images/smoke_ied.png",
	ItemType = "Throwables",
	DisplayName = T(603817580280, --[[ModItemInventoryItemCompositeDef SmokeGrenade_IED DisplayName]] "Improvised Smoke Grenade"),
	DisplayNamePlural = T(521720469032, --[[ModItemInventoryItemCompositeDef SmokeGrenade_IED DisplayNamePlural]] "Improvised Smoke Grenades"),
	AdditionalHint = T(953201278809, --[[ModItemInventoryItemCompositeDef SmokeGrenade_IED AdditionalHint]] "<EO_description_hints>\n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Ranged attacks passing through gas become <color EmStyle>grazing</color> hits\n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> No damage\n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Almost silent"),
	UnitStat = "Explosives",
	Cost = 600,
	CanAppearInShop = true,
	Tier = 2,
	RestockWeight = 25,
	CategoryPair = "Grenade",
	MinMishapChance = -2,
	MaxMishapChance = 18,
	MinMishapRange = 0,
	CenterUnitDamageMod = 0,
	CenterObjDamageMod = 0,
	AreaUnitDamageMod = 0,
	AreaObjDamageMod = 0,
	PenetrationClass = 1,
	BaseDamage = 0,
	Scatter = 4,
	AttackAP = 4000,
	InaccurateMaxOffset = 3000,
	Noise = 0,
	aoeType = "smoke",
	Entity = "Weapon_SmokeGrenade_Test",
	ActionIcon = "UI/Icons/Hud/smoke_grenade",
	r_timer = 3500,
	r_mass = 610,
	r_shape = "Cylindrical",
}

