UndefineClass('TearGasGrenade_IED')
DefineClass.TearGasGrenade_IED = {
	__parents = { "Grenade" },
	__generated_by_class = "ModItemInventoryItemCompositeDef",


	object_class = "Grenade",
	Repairable = false,
	Reliability = 100,
	Icon = "Mod/RATONADE/Images/TEAR2_ied.png",
	ItemType = "GrenadeGas",
	DisplayName = T(992290877366, --[[ModItemInventoryItemCompositeDef TearGasGrenade_IED DisplayName]] "Improvised Tear Gas Grenade"),
	DisplayNamePlural = T(520192725614, --[[ModItemInventoryItemCompositeDef TearGasGrenade_IED DisplayNamePlural]] "Improvised Tear Gas Grenades"),
	AdditionalHint = T(468937308243, --[[ModItemInventoryItemCompositeDef TearGasGrenade_IED AdditionalHint]] "<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Inflicts <color EmStyle>Blinded</color>\n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Ranged attacks passing through gas become <color EmStyle>grazing</color> hits\n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> No damage\n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> High mishap chance\n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Almost silent"),
	UnitStat = "Explosives",
	Cost = 800,
	CanAppearInShop = true,
	Tier = 2,
	RestockWeight = 25,
	CategoryPair = "Grenade",
	MinMishapChance = 2,
	MaxMishapChance = 30,
	MinMishapRange = 0,
	CenterUnitDamageMod = 0,
	CenterObjDamageMod = 0,
	AreaUnitDamageMod = 0,
	AreaObjDamageMod = 0,
	PenetrationClass = 1,
	BaseDamage = 0,
	Scatter = 4,
	AttackAP = 4000,
	InaccurateMaxOffset = 4000,
	Noise = 0,
	aoeType = "teargas",
	Entity = "Weapon_MolotovCocktail",
	ActionIcon = "UI/Icons/Hud/tear_gas_grenade",
	r_timer = 4000,
	r_mass = 610,
	r_shape = "Cylindrical",
}

