UndefineClass('TimedC4')
DefineClass.TimedC4 = {
	__parents = { "ThrowableTrapItem" },
	__generated_by_class = "ModItemInventoryItemCompositeDef",


	object_class = "ThrowableTrapItem",
	Repairable = false,
	Reliability = 100,
	Icon = "UI/Icons/Items/timed_c4",
	ItemType = "Grenade",
	DisplayName = T(559267717229, --[[ModItemInventoryItemCompositeDef TimedC4 DisplayName]] "Timed C4"),
	DisplayNamePlural = T(434330146200, --[[ModItemInventoryItemCompositeDef TimedC4 DisplayNamePlural]] "Timed C4"),
	AdditionalHint = T(528995647980, --[[ModItemInventoryItemCompositeDef TimedC4 AdditionalHint]] "<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Explodes after 1 turn (or 5 seconds out of combat)"),
	UnitStat = "Explosives",
	Cost = 1200,
	CanAppearInShop = true,
	Tier = 2,
	MaxStock = 1,
	RestockWeight = 10,
	CategoryPair = "Grenade",
	MinMishapChance = -2,
	MaxMishapChance = 18,
	MinMishapRange = 0,
	MaxMishapRange = 3,
	AttackAP = 4000,
	BaseRange = 3,
	ThrowMaxRange = 12,
	CanBounce = false,
	InaccurateMaxOffset = 4000,
	IgnoreCoverReduction = 1,
	Noise = 30,
	Entity = "Explosive_C4",
	ActionIcon = "UI/Icons/Hud/throw_timed_explosives",
	r_mass = 2000,
	r_shape = "Brick",
	r_shrap_num = 200,
	TriggerType = "Timed",
	ExplosiveType = "C4",
}

