UndefineClass('TimedPETN')
DefineClass.TimedPETN = {
	__parents = { "ThrowableTrapItem" },
	__generated_by_class = "ModItemInventoryItemCompositeDef",


	object_class = "ThrowableTrapItem",
	Repairable = false,
	Reliability = 100,
	Icon = "UI/Icons/Items/timed_petn",
	ItemType = "Grenade",
	DisplayName = T(371795015084, --[[ModItemInventoryItemCompositeDef TimedPETN DisplayName]] "Timed PETN"),
	DisplayNamePlural = T(922603486603, --[[ModItemInventoryItemCompositeDef TimedPETN DisplayNamePlural]] "Timed PETN"),
	AdditionalHint = T(200584217333, --[[ModItemInventoryItemCompositeDef TimedPETN AdditionalHint]] "<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Explodes after 1 turn (or 5 seconds out of combat)"),
	UnitStat = "Explosives",
	Cost = 1500,
	CanAppearInShop = true,
	Tier = 3,
	MaxStock = 1,
	RestockWeight = 10,
	CategoryPair = "Grenade",
	MinMishapChance = -2,
	MaxMishapChance = 18,
	MinMishapRange = 0,
	MaxMishapRange = 3,
	AttackAP = 4000,
	BaseRange = 3,
	ThrowMaxRange = 12,
	CanBounce = false,
	InaccurateMaxOffset = 4000,
	Noise = 30,
	Entity = "Explosive_PETN",
	ActionIcon = "UI/Icons/Hud/throw_timed_explosives",
	r_mass = 1800,
	r_shape = "Brick",
	TriggerType = "Timed",
	ExplosiveType = "PETN",
}

