UndefineClass('TimedTNT')
DefineClass.TimedTNT = {
	__parents = { "ThrowableTrapItem" },
	__generated_by_class = "ModItemInventoryItemCompositeDef",


	object_class = "ThrowableTrapItem",
	Repairable = false,
	Reliability = 100,
	Icon = "UI/Icons/Items/timed_tnt",
	ItemType = "Grenade",
	DisplayName = T(533173120854, --[[ModItemInventoryItemCompositeDef TimedTNT DisplayName]] "Timed TNT"),
	DisplayNamePlural = T(818362435719, --[[ModItemInventoryItemCompositeDef TimedTNT DisplayNamePlural]] "Timed TNT"),
	AdditionalHint = T(123704050861, --[[ModItemInventoryItemCompositeDef TimedTNT AdditionalHint]] "<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Explodes after 1 turn (or 5 seconds out of combat)\n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> High mishap chance"),
	UnitStat = "Explosives",
	Cost = 850,
	CanAppearInShop = true,
	Tier = 2,
	MaxStock = 1,
	RestockWeight = 20,
	CategoryPair = "Grenade",
	MinMishapChance = 2,
	MaxMishapChance = 30,
	MinMishapRange = 0,
	MaxMishapRange = 3,
	AttackAP = 4000,
	BaseRange = 3,
	ThrowMaxRange = 12,
	CanBounce = false,
	InaccurateMaxOffset = 4000,
	Noise = 30,
	Entity = "Explosive_TNT",
	ActionIcon = "UI/Icons/Hud/throw_timed_explosives",
	r_mass = 1500,
	r_shape = "Long",
	r_shrap_num = 200,
	TriggerType = "Timed",
}

