UndefineClass('TNT')
DefineClass.TNT = {
	__parents = { "ExplosiveSubstance" },
	__generated_by_class = "ModItemInventoryItemCompositeDef",


	object_class = "ExplosiveSubstance",
	Repairable = false,
	Icon = "UI/Icons/Items/tnt",
	DisplayName = T(464151031897, --[[ModItemInventoryItemCompositeDef TNT DisplayName]] "TNT"),
	DisplayNamePlural = T(897946100206, --[[ModItemInventoryItemCompositeDef TNT DisplayNamePlural]] "TNT"),
	Description = T(579110878277, --[[ModItemInventoryItemCompositeDef TNT Description]] "The go-to tool of railroad builders and Wild West moustache villains, the TNT is easy to find, use and abuse."),
	AdditionalHint = T(728674085231, --[[ModItemInventoryItemCompositeDef TNT AdditionalHint]] "<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Combine with a Detonator type to create an Explosive\n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Larger blast area"),
	UnitStat = "Explosives",
	Cost = 200,
	CanAppearInShop = true,
	MaxStock = 2,
	RestockWeight = 60,
	CategoryPair = "Components",
	CenterUnitDamageMod = 130,
	CenterObjDamageMod = 300,
	CenterAppliedEffects = {
		"Revealed",
		"KnockDown",
		"Exposed",
		"Bleeding",
		"CancelShot",
		"Suppressed",
		"SeverelySuppressed",
	},
	AreaOfEffect = 5,
	AreaObjDamageMod = 300,
	AreaAppliedEffects = {
		"Revealed",
		"KnockDown",
		"Exposed",
		"Bleeding",
		"CancelShot",
		"Suppressed",
		"SeverelySuppressed",
	},
	PenetrationClass = 4,
	DeathType = "BlowUp",
	BaseDamage = 38,
	Noise = 30,
}

